/**
 * /src/types/index.ts — Cross-agent interface contracts
 *
 * This is the most critical file in the project. It is the sole contract
 * between all agents. Rules:
 *   - No agent modifies this file unilaterally
 *   - Changes require a PR reviewed by all active agents
 *   - No implementation code — types and interfaces only
 */

// ─── Primitives ───────────────────────────────────────────────────────────────

/**
 * The six built-in model identifiers that ship with Roundtable.
 *
 * This is a closed union — Atlas owns the concrete implementations for each
 * value. Gate owns the credential mapping for each value. Adding a new built-in
 * provider requires a types PR (Arch), an Atlas implementation, and a Gate
 * credential entry.
 *
 * @see ModelId for the open union that includes user-defined custom providers.
 */
export type BuiltInModelId =
  | 'claude'
  | 'gpt-5.5'
  | 'gemini'
  | 'grok'
  | 'deepseek'
  | 'mistral';

/**
 * Identity token for any model — built-in or user-configured custom.
 *
 * `BuiltInModelId` members remain valid values and continue to receive IDE
 * autocomplete. Custom provider IDs are arbitrary strings chosen by Gate when
 * the user configures a new OpenAI-compatible endpoint (e.g. "openrouter-1",
 * "local-ollama"). Gate is responsible for generating unique IDs and for
 * ensuring no custom ID collides with a `BuiltInModelId` value.
 *
 * The `(string & {})` intersection is the TypeScript open-union idiom: it
 * preserves autocomplete on the named members while accepting any string.
 * Code that switches on known values (e.g. `case 'claude':`) continues to
 * type-check correctly. Code that needs to discriminate built-ins from custom
 * providers must use `BuiltInModelId` explicitly.
 *
 * Consumers must NOT use `ModelId` as an index type in a `Record<>` that
 * expects exhaustive coverage — use `BuiltInModelId` for that or a `Map`.
 */
export type ModelId = BuiltInModelId | (string & {});

export type InteractionMode = 'parallel' | 'manual' | 'auto-chain';

export type MessageRole = 'user' | 'assistant';

/**
 * Display metadata for a single interaction mode. Aria uses a typed registry
 * of these to render the mode-switcher control and tooltips (issue #12).
 */
export interface InteractionModeConfig {
  mode: InteractionMode;
  /** Short label shown in the switcher button. */
  label: string;
  /** One-sentence description shown in the tooltip. */
  description: string;
}

/**
 * A single step in an auto-chain sequence.
 * Defines which model speaks at this position and what role it plays.
 */
export interface ChainStep {
  /** Index of this step in the chain (0-based). */
  stepIndex: number;
  modelId: ModelId;
  /**
   * When true, this model's response is appended to the shared context before
   * the next step runs. When false the step runs in isolation.
   */
  appendToContext: boolean;
}

/**
 * Configuration for an auto-chain run. Atlas uses this to sequence
 * model calls; Aria may read it to render chain progress (issue #14).
 */
export interface AutoChainConfig {
  /** Ordered steps to execute. */
  steps: ChainStep[];
  /**
   * Maximum number of times the full step sequence may repeat before
   * the chain terminates automatically. 1 = single pass.
   */
  maxPasses: number;
}

/**
 * The six built-in credential keys, one per built-in provider.
 * Gate maps `BuiltInModelId` values to these keys in `MODEL_CREDENTIAL_MAP`.
 *
 * @see CredentialKey for the open union that includes user-defined keys.
 */
export type BuiltInCredentialKey =
  | 'anthropic'
  | 'openai'
  | 'google'
  | 'xai'
  | 'deepseek'
  | 'mistral';

/**
 * Identity token for an API credential — built-in or user-configured.
 *
 * Custom providers use credential keys of the form `"custom:<providerId>"`,
 * generated by Gate when the user configures a new endpoint. Gate is
 * responsible for storage and retrieval under these keys.
 *
 * Same open-union idiom as `ModelId`: named members get autocomplete;
 * arbitrary strings are accepted for custom provider keys.
 */
export type CredentialKey = BuiltInCredentialKey | (string & {});

export type ExportFormat = 'markdown' | 'html';

// ─── Token usage ──────────────────────────────────────────────────────────────

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
}

/**
 * Running session totals for a single model. Aria reads this to display
 * per-model usage in the UI (issue #15 / #16).
 */
export interface SessionTokenUsage {
  modelId: ModelId;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
}

// ─── Messages ─────────────────────────────────────────────────────────────────

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  /** Present on assistant messages. */
  modelId?: ModelId;
  timestamp: number;
  /** Populated when isDone is true on the final StreamChunk. */
  tokenUsage?: TokenUsage;
  /** Phase 2 — directed replies. */
  targetModelId?: ModelId;
  /** True while the message is still streaming. */
  isStreaming?: boolean;
  /** Set on assistant messages when the stream terminated with an error. */
  error?: ModelError;
}

// ─── Model version selection ───────────────────────────────────────────────────

/**
 * A single selectable version of a model, surfaced in the model config panel.
 *
 * Atlas populates these on each ModelRegistryEntry. Aria renders them as a
 * version picker control inside the per-model settings panel. Gate persists the
 * user's selection via `selectedVersionId` on `ModelConfig`.
 *
 * `id` must be the exact API-level model string passed to the provider endpoint
 * (e.g. "claude-opus-4-5", "gpt-4o", "gemini-2.5-pro"). `displayName` is the
 * human-readable label shown in the picker. `description` is an optional
 * one-liner surfaced as a subtitle or tooltip.
 *
 * Design note: available versions are static (known at build time). This type
 * therefore lives on the MODEL_REGISTRY entry in Atlas, NOT on `ModelProvider`.
 * Adding `getAvailableVersions()` to `ModelProvider` would force every runtime
 * provider instance to carry static data it has no business owning, and would
 * complicate mocking in tests. If a future provider needs dynamic version
 * discovery (e.g. fetching from a versions endpoint), surface that as a
 * separate interface at that time — do not extend ModelProvider prematurely.
 */
export interface ModelVersionOption {
  /** API-level model string, e.g. "claude-opus-4-5", "gpt-4o". */
  id: string;
  /** Human-readable label shown in the version picker, e.g. "Claude Opus 4". */
  displayName: string;
  /** Optional one-liner shown as subtitle or tooltip, e.g. "Most capable". */
  description?: string;
}

// ─── Model config ─────────────────────────────────────────────────────────────

export interface ModelConfig {
  modelId: ModelId;
  /** Display name shown in UI. */
  name: string;
  /** Tailwind color token, e.g. "violet" or "sky". */
  color: string;
  /** Phase 2 — per-model system prompt. */
  systemPrompt?: string;
  isActive: boolean;
  /**
   * The `id` of the `ModelVersionOption` the user has selected for this model.
   * Absence means "use the provider's default version" (i.e. whatever Atlas
   * sends when no explicit model string override is applied).
   *
   * Gate reads and writes this field. Atlas reads it in `sendMessage` to choose
   * which API model string to pass to the provider endpoint. Aria reads it to
   * highlight the active option in the version picker.
   */
  selectedVersionId?: string;
}

// ─── Provider roster — Gate stores, Aria renders, Atlas dispatches ────────────

/**
 * Persisted configuration for a single built-in provider in the user's roster.
 *
 * Gate writes one of these per built-in provider the user has configured.
 * `isVisible` controls whether the provider appears in the Aria model selector
 * and can be added to new conversations — it does NOT remove the provider from
 * Atlas's dispatch table. A non-visible provider will simply never be active.
 *
 * `selectedVersionId` is the API-level model string the user last chose for
 * this provider (e.g. "claude-sonnet-4-6"). Absence means "use provider default".
 *
 * `credentialKey` is the `BuiltInCredentialKey` for the provider. Gate derives
 * this from `MODEL_CREDENTIAL_MAP` at write time so Atlas and Aria never need
 * to re-derive it.
 */
export interface BuiltInProviderConfig {
  kind: 'builtin';
  /** One of the six built-in model identifiers. */
  modelId: BuiltInModelId;
  /** The credential key used to retrieve the API key from Gate. */
  credentialKey: BuiltInCredentialKey;
  /**
   * The `id` of the `ModelCatalogEntry` the user has selected for this provider.
   * Absence means "use the provider's default version."
   */
  selectedVersionId?: string;
  /**
   * Whether this provider is visible in the Aria model selector.
   * Default: true. Users can set this to false to hide a built-in they do not use.
   */
  isVisible: boolean;
}

/**
 * Persisted configuration for a user-configured custom OpenAI-compatible provider.
 *
 * Gate writes one of these when the user adds a custom endpoint (OpenRouter,
 * Ollama, LM Studio, private endpoint, etc.). Atlas instantiates a dynamic
 * provider for each entry in the roster whose kind is 'custom'.
 *
 * `id` is a Gate-generated unique string (e.g. "custom-openrouter-1").
 * It serves as the `ModelId` for this provider everywhere in the system.
 * Gate must ensure no `id` collides with a `BuiltInModelId` value.
 *
 * `credentialKey` is Gate-generated and follows the pattern `"custom:<id>"`.
 * If the endpoint requires no authentication, `credentialKey` may be absent.
 *
 * `modelString` is the exact model identifier sent to the provider endpoint
 * (e.g. "meta-llama/llama-3-70b-instruct" for OpenRouter). This is distinct
 * from `id` — `id` identifies the provider config record; `modelString` is
 * the API parameter.
 *
 * `color` is an optional CSS custom-property token name (e.g. "accent-other")
 * or 6-digit hex string. Absence means Aria uses the 'accent-other' fallback.
 */
export interface CustomProviderConfig {
  kind: 'custom';
  /** Gate-generated unique identifier. This is the `ModelId` for this provider. */
  id: string;
  /** Human-readable label shown in the model selector and message bubbles. */
  displayName: string;
  /** Full URL of the OpenAI-compatible /chat/completions endpoint. */
  endpointUrl: string;
  /** Gate-generated credential key for this provider's API key (pattern: "custom:<id>"). */
  credentialKey?: string;
  /**
   * The model string sent to the provider endpoint (e.g. "llama-3-70b-instruct").
   * For providers like Ollama that use short names, this is exactly what they expect.
   */
  modelString: string;
  /**
   * Optional accent color. CSS custom-property token (e.g. "accent-other")
   * or 6-digit hex string (e.g. "#FF5500"). Aria applies 'accent-other' when absent.
   */
  color?: string;
}

/**
 * A single entry in the user's provider roster.
 * Discriminated on `kind` — 'builtin' or 'custom'.
 */
export type ProviderConfig = BuiltInProviderConfig | CustomProviderConfig;

/**
 * The user's complete configured provider roster.
 *
 * Gate owns storage (localStorage key: "roundtable:provider-roster").
 * Aria reads it to populate the model selector and conversation model list.
 * Atlas reads it to resolve which providers to instantiate and dispatch to.
 *
 * Ordering: the array order is the display order in the Aria model selector.
 * Gate may allow the user to reorder entries; Atlas must respect the order when
 * building the active provider list for a conversation.
 *
 * An empty roster is valid — the user has configured no providers yet.
 * Aria should surface a "configure providers" onboarding prompt in this state.
 */
export type ProviderRoster = ProviderConfig[];

// ─── Model catalog — model version entries from any source ────────────────────

/**
 * Provenance of a `ModelCatalogEntry` — where the version information came from.
 *
 * - 'bundled'  — shipped with Roundtable at build time (Atlas's static registry)
 * - 'remote'   — fetched from a remote `models.json` at runtime (raw.githubusercontent.com)
 * - 'live-api' — discovered via a provider's live models endpoint (e.g. OpenRouter /api/v1/models)
 */
export type ModelCatalogSource = 'bundled' | 'remote' | 'live-api';

/**
 * Normalized shape for a single selectable model version, regardless of source.
 *
 * This is the richer replacement for `ModelVersionOption`. It carries the same
 * `id`, `displayName`, and `description` fields as `ModelVersionOption`, plus
 * `source` for provenance tracking and an optional `contextWindow` for display.
 *
 * Atlas uses this in its dynamic registry (replacing the static `ModelVersionOption[]`
 * on `ModelRegistryEntry`) when it fetches versions from remote sources.
 * Aria renders these in the version picker the same way it renders `ModelVersionOption`.
 * Gate persists the selected `id` via `selectedVersionId` on `ProviderConfig`.
 *
 * `id` must be the exact API-level model string passed to the provider endpoint
 * (e.g. "claude-opus-4-8", "meta-llama/llama-3-70b-instruct").
 *
 * Backward compat: `ModelVersionOption` is retained for Atlas's static built-in
 * registry. New code that handles dynamic version lists should use `ModelCatalogEntry`.
 * Aria's version picker accepts either type by reading only `id`, `displayName`, and
 * `description` — both shapes are structurally compatible with those three fields.
 */
export interface ModelCatalogEntry {
  /** API-level model string, e.g. "claude-opus-4-8", "meta-llama/llama-3-70b-instruct". */
  id: string;
  /** Human-readable label shown in the version picker, e.g. "Claude Opus 4". */
  displayName: string;
  /** Optional one-liner shown as subtitle or tooltip, e.g. "Most capable". */
  description?: string;
  /** Where this entry originated. */
  source: ModelCatalogSource;
  /** Optional context window size in tokens, shown in the version picker if present. */
  contextWindow?: number;
}

// ─── Conversation ─────────────────────────────────────────────────────────────

export interface Conversation {
  id: string;
  /** Auto-generated from the first user message. */
  title?: string;
  messages: Message[];
  models: ModelConfig[];
  interactionMode: InteractionMode;
  /** Ghost mode: nothing is ever written to storage. */
  isGhost: boolean;
  createdAt: number;
  updatedAt: number;
  /** Set when the conversation is archived. */
  archivedAt?: number;
  /** Phase 3 — group/folder assignment. */
  groupId?: string;
}

// ─── ConversationStore — consumed by Aria ────────────────────────────────────

/**
 * Read-only view of conversation state exposed to the UI layer.
 * Vault owns the implementation; Aria consumes it (e.g. via React context).
 */
export interface ConversationStore {
  conversations: Conversation[];
  activeConversationId: string | null;
  getConversation(id: string): Conversation | undefined;
  getActiveConversation(): Conversation | undefined;
  /**
   * Returns running session token totals for every active model in the given
   * conversation. Aria uses this for the per-model usage display (issue #15 / #16).
   * Atlas also exports a standalone getSessionTokenUsage() utility from
   * @/models for convenience (documented exception to the boundary rule).
   */
  getSessionTokenUsage(conversationId: string): SessionTokenUsage[];
}

// ─── Streaming — sendMessage plumbing ─────────────────────────────────────────

export interface StreamChunk {
  modelId: ModelId;
  /** Incremental text delta. */
  content: string;
  isDone: boolean;
  /** Present only when isDone is true. */
  tokenUsage?: TokenUsage;
  error?: ModelError;
}

export type StreamHandler = (chunk: StreamChunk) => void;

// ─── sendMessage — Atlas exposes, Aria calls ──────────────────────────────────

export interface SendMessageOptions {
  conversationId: string;
  content: string;
  /** Phase 2 — omit to broadcast to all active models. */
  targetModelId?: ModelId;
  /** Phase 2 — omit for parallel/manual modes. Atlas uses this to sequence auto-chain calls. */
  chainConfig?: AutoChainConfig;
}

/**
 * Top-level send function. Fans out to all active ModelProviders in parallel.
 * Streams each model's response via onChunk. Resolves when all models are done.
 */
export type SendMessageFn = (
  options: SendMessageOptions,
  onChunk: StreamHandler
) => Promise<void>;

// ─── ModelProvider — Atlas implements per model ───────────────────────────────

export type ModelErrorCode =
  | 'auth_failure'
  | 'rate_limit'
  | 'network_error'
  | 'context_length_exceeded'
  | 'unknown';

export interface ModelError {
  code: ModelErrorCode;
  message: string;
}

export interface ModelProviderConfig {
  modelId: ModelId;
  name: string;
  color: string;
  /** The CredentialKey used to fetch the API key from Gate. */
  credentialKey: CredentialKey;
}

export interface ModelProvider {
  readonly config: ModelProviderConfig;
  /**
   * Sends messages to the underlying model and streams the response.
   * Resolves with token usage once the stream is complete.
   * Rejects if a non-recoverable error occurs (auth, network, etc.).
   */
  sendMessage(
    messages: Message[],
    systemPrompt: string | undefined,
    onChunk: StreamHandler
  ): Promise<{ tokenUsage?: TokenUsage }>;
}

// ─── StorageProvider — Vault implements ───────────────────────────────────────

/**
 * Serialized content produced by converting a conversation to a given format.
 * The caller decides what to do with it — trigger a download, stream over HTTP,
 * write to disk, etc.
 */
export interface ExportedConversation {
  /** The serialized conversation body (UTF-8 string). */
  content: string;
  /** Suggested filename including extension, e.g. "my-chat.md". */
  filename: string;
  /** MIME type of the content, e.g. "text/markdown;charset=utf-8". */
  mimeType: string;
}

/**
 * Core persistence contract. Vault owns the implementation; all other agents
 * interact with storage exclusively through this interface.
 *
 * Design invariants:
 *   - All methods are async. localStorage is synchronous under the hood, but
 *     the async boundary is load-bearing: it allows a future ServerStorageProvider
 *     to substitute without interface changes.
 *   - Ghost-mode guard: `saveConversation` silently no-ops when
 *     `conversation.isGhost === true`. All other write methods are not
 *     ghost-aware — callers must never pass a ghost conversation ID to them.
 *   - Upsert semantics: `saveConversation` creates or fully replaces a record.
 *     To update a single field (e.g. `groupId`), load the conversation, mutate
 *     the local copy, and call `saveConversation` with the full updated object.
 *     There is no `patchConversation`.
 *   - Idempotent deletes: `deleteConversation` on a non-existent ID is a no-op.
 *   - Export is side-effect-free: `exportConversation` returns serialized content
 *     and does NOT trigger a browser download. Download is a DOM concern that a
 *     ServerStorageProvider cannot fulfill. Vault's LocalStorageProvider wraps
 *     the return value in a download trigger; other consumers may stream it,
 *     write it to disk, or return it over HTTP.
 */
export interface StorageProvider {
  /**
   * Persist a conversation (create or replace — upsert semantics).
   *
   * Ghost-mode guard: if `conversation.isGhost === true`, returns immediately
   * without writing anything. This is the canonical guard point — callers do
   * not need to check `isGhost` before calling.
   *
   * Throws if the storage backend is full (e.g. QuotaExceededError in
   * localStorage). The caller is responsible for surfacing this to the user.
   */
  saveConversation(conversation: Conversation): Promise<void>;

  /**
   * Load a single conversation by ID.
   *
   * Returns `null` if no record exists for the given ID, or if the stored
   * data is present but corrupt (parse failure). Does not throw on missing or
   * corrupt data — callers should treat `null` as "not found".
   */
  loadConversation(id: string): Promise<Conversation | null>;

  /**
   * Return all stored conversations, sorted newest-first by `updatedAt`.
   *
   * Conversations whose underlying data is corrupt or missing are silently
   * omitted so the list remains usable even when storage is partially damaged.
   * Archived conversations (those with `archivedAt` set) are included —
   * filtering by archive status is the UI's responsibility.
   * Ghost conversations are never included (they are not persisted).
   */
  listConversations(): Promise<Conversation[]>;

  /**
   * Permanently remove a conversation from storage.
   *
   * No-op if the conversation does not exist. Removes the record from both
   * the index and its data key. Does not cascade to any related records.
   */
  deleteConversation(id: string): Promise<void>;

  /**
   * Mark a conversation as archived by setting its `archivedAt` timestamp.
   *
   * No-op if the conversation does not exist. Archived conversations remain
   * in the index and are returned by `listConversations` — they are not
   * deleted. The UI is responsible for showing/hiding archived conversations.
   * Group membership (`groupId`) is preserved on archive.
   *
   * To reverse, call `unarchiveConversation`.
   */
  archiveConversation(id: string): Promise<void>;

  /**
   * Clear the `archivedAt` timestamp on a conversation, returning it to
   * active status.
   *
   * No-op if the conversation does not exist or was not archived.
   */
  unarchiveConversation(id: string): Promise<void>;

  /**
   * Serialize a conversation to the requested format and return the result.
   *
   * Returns `null` if the conversation does not exist.
   *
   * Side-effect-free: does NOT trigger a browser download. The caller decides
   * what to do with the content — Vault's LocalStorageProvider wraps this in a
   * download trigger; a ServerStorageProvider would stream it over HTTP.
   * The `filename` and `mimeType` fields are hints that callers may override.
   */
  exportConversation(id: string, format: ExportFormat): Promise<ExportedConversation | null>;
}

// ─── Themes ───────────────────────────────────────────────────────────────────

export type ThemeId = 'slate' | 'linen' | 'midnight' | 'ash' | 'ember' | 'chalk' | 'outrun';

/** Full token schema for a Roundtable theme. All fields required. */
export interface CustomThemeJSON {
  name: string;
  mode: 'dark' | 'light';
  surfaces: {
    background: string;
    card: string;
    sidebar: string;
    input: string;
  };
  text: {
    primary: string;
    secondary: string;
    muted: string;
    inverse: string;
  };
  borders: {
    default: string;
    subtle: string;
    strong: string;
  };
  accents: {
    'model-claude': string;
    'model-gpt': string;
    'model-gemini': string;
    'model-other': string;
    'model-grok': string;
    'model-deepseek': string;
    'model-mistral': string;
  };
  interactive: {
    hover: string;
    active: string;
    focusRing: string;
  };
  semantic: {
    success: string;
    warning: string;
    /** Foreground text color for error states (bright red, reads on dark surfaces). */
    error: string;
    /** Background color for destructive buttons (dark red, supports white text at 4.5:1+). */
    'error-bg': string;
    info: string;
  };
  radius: {
    sm: string;
    md: string;
    lg: string;
    full: string;
  };
  spacing: {
    '1': string;
    '2': string;
    '3': string;
    '4': string;
    '6': string;
    '8': string;
    '12': string;
    '16': string;
  };
  shadow: {
    none: 'none';
    sm: string;
    md: string;
    lg: string;
  };
  timing: {
    instant: string;
    fast: string;
    medium: string;
    slow: string;
  };
}

export interface ThemePreferences {
  activeThemeId: ThemeId;
  customTheme?: CustomThemeJSON;
}

// ─── Credentials — Gate implements ───────────────────────────────────────────

/**
 * Retrieve a stored API key. Returns undefined if not set.
 */
export type GetCredentialsFn = (key: CredentialKey) => string | undefined;

/**
 * Persist an API key to localStorage. Never transmit, log, or export keys.
 */
export type SaveCredentialsFn = (key: CredentialKey, value: string) => void;

/**
 * Remove a stored API key.
 */
export type ClearCredentialsFn = (key: CredentialKey) => void;

// ─── User preferences — Gate implements, Aria consumes ───────────────────────

/**
 * Controls when per-message token counts are visible in the chat UI.
 *
 * - 'always' — token counts shown unconditionally on all completed model bubbles
 * - 'active' — hover reveals on desktop, tap reveals on mobile (default;
 *              matches the hover-reveal behavior shipped in #16)
 * - 'never'  — token count element removed from DOM entirely (not hidden with CSS)
 *
 * Gate reads and writes this value; Aria reads it to determine render behavior.
 */
export type TokenCountVisibility = 'always' | 'active' | 'never';

/**
 * Persistent user preferences. Gate owns storage (localStorage); Aria reads
 * these values to drive conditional rendering and display behavior.
 *
 * Default values when no preference is stored:
 *   tokenCountVisibility: 'active'
 */
export interface UserPreferences {
  tokenCountVisibility: TokenCountVisibility;
}

// ─── Model accent color overrides — Gate implements, Aria consumes ────────────

/**
 * User-chosen accent colors that override the active theme's accent tokens.
 * Partial record — only models with active overrides are present.
 * Absence of a key means "use the active theme's default accent for that model."
 * Values are 6-digit hex strings (e.g. "#FF5500").
 *
 * Persisted by Gate under the localStorage key "roundtable:model-accent-colors".
 * Applied by Aria as a second CSS custom-property pass after the theme loader
 * runs — overriding `--accent-{model}` only for models present in this record.
 */
export type ModelAccentColors = Partial<Record<ModelId, string>>;

/**
 * Retrieve all stored model accent color overrides.
 * Returns {} when no overrides are stored or if the stored value is corrupt.
 * Gate implements; Aria calls this on app load and after every theme switch.
 */
export type GetModelAccentColorsFn = () => ModelAccentColors;

/**
 * Persist a single model accent color override.
 * Gate validates the hex value matches /^#[0-9A-Fa-f]{6}$/ before writing.
 * Throws TypeError on invalid hex — Aria must validate before calling.
 * Gate implements; Aria calls this when the user confirms a color selection.
 */
export type SetModelAccentColorFn = (modelId: ModelId, hex: string) => void;

/**
 * Remove the stored accent color override for a single model.
 * No-op if the model has no stored override.
 * Gate implements; Aria calls this when the user clicks "Reset to theme default"
 * in the color picker popover for a specific model.
 */
export type ClearModelAccentColorFn = (modelId: ModelId) => void;

/**
 * Remove all stored model accent color overrides.
 * Removes the entire "roundtable:model-accent-colors" localStorage key.
 * Gate implements; Aria calls this from the "Reset all model colors to theme
 * defaults" control in the Settings panel.
 */
export type ClearAllModelAccentColorsFn = () => void;
