/**
 * /src/types/index.ts — Cross-agent interface contracts
 *
 * This is the most critical file in the project. It is the sole contract
 * between all agents. Rules:
 *   - No agent modifies this file unilaterally
 *   - Changes require a PR reviewed by all active agents
 *   - No implementation code — types and interfaces only
 */

// ─── Primitives ───────────────────────────────────────────────────────────────

/**
 * The six built-in model identifiers that ship with Roundtable.
 *
 * This is a closed union — Atlas owns the concrete implementations for each
 * value. Gate owns the credential mapping for each value. Adding a new built-in
 * provider requires a types PR (Arch), an Atlas implementation, and a Gate
 * credential entry.
 *
 * **Runtime enumeration — single-source rule:** Any Gate module that needs a
 * runtime collection of these values (e.g. a `Set` for deserialization
 * validation, an array for iteration) must import from a single canonical Gate
 * utility rather than re-enumerating the string literals. Duplicating the list
 * across multiple files creates a silent drift hazard: adding a new member to
 * this union does not cause a compiler error in files that maintain their own
 * `Set`, so a new provider passes type-checking but fails runtime validation
 * silently. `MODEL_CREDENTIAL_MAP` in `@/auth/credentials` is the one allowed
 * exception — its `Record<BuiltInModelId, ...>` type enforces exhaustiveness
 * at compile time and is safe as a separate declaration.
 *
 * @see ModelId for the open union that includes user-defined custom providers.
 */
export type BuiltInModelId =
  | 'claude'
  | 'gpt-5.5'
  | 'gemini'
  | 'grok'
  | 'deepseek'
  | 'mistral';

/**
 * Identity token for any model — built-in or user-configured custom.
 *
 * `BuiltInModelId` members remain valid values and continue to receive IDE
 * autocomplete. Custom provider IDs are arbitrary strings chosen by Gate when
 * the user configures a new OpenAI-compatible endpoint (e.g. "openrouter-1",
 * "local-ollama"). Gate is responsible for generating unique IDs and for
 * ensuring no custom ID collides with a `BuiltInModelId` value.
 *
 * The `(string & {})` intersection is the TypeScript open-union idiom: it
 * preserves autocomplete on the named members while accepting any string.
 * Code that switches on known values (e.g. `case 'claude':`) continues to
 * type-check correctly. Code that needs to discriminate built-ins from custom
 * providers must use `BuiltInModelId` explicitly.
 *
 * Consumers must NOT use `ModelId` as an index type in a `Record<>` that
 * expects exhaustive coverage — use `BuiltInModelId` for that or a `Map`.
 */
export type ModelId = BuiltInModelId | (string & {});

export type InteractionMode = 'parallel' | 'manual' | 'auto-chain';

export type MessageRole = 'user' | 'assistant';

/**
 * Display metadata for a single interaction mode. Aria uses a typed registry
 * of these to render the mode-switcher control and tooltips (issue #12).
 */
export interface InteractionModeConfig {
  mode: InteractionMode;
  /** Short label shown in the switcher button. */
  label: string;
  /** One-sentence description shown in the tooltip. */
  description: string;
}

/**
 * A single step in an auto-chain sequence.
 * Defines which model speaks at this position and what role it plays.
 */
export interface ChainStep {
  /** Index of this step in the chain (0-based). */
  stepIndex: number;
  modelId: ModelId;
  /**
   * When true, this model's response is appended to the shared context before
   * the next step runs. When false the step runs in isolation.
   */
  appendToContext: boolean;
}

/**
 * Configuration for an auto-chain run. Atlas uses this to sequence
 * model calls; Aria may read it to render chain progress (issue #14).
 */
export interface AutoChainConfig {
  /** Ordered steps to execute. */
  steps: ChainStep[];
  /**
   * Maximum number of times the full step sequence may repeat before
   * the chain terminates automatically. 1 = single pass.
   */
  maxPasses: number;
}

/**
 * The six built-in credential keys, one per built-in provider.
 * Gate maps `BuiltInModelId` values to these keys in `MODEL_CREDENTIAL_MAP`.
 *
 * @see CredentialKey for the open union that includes user-defined keys.
 */
export type BuiltInCredentialKey =
  | 'anthropic'
  | 'openai'
  | 'google'
  | 'xai'
  | 'deepseek'
  | 'mistral';

/**
 * Identity token for an API credential — built-in or user-configured.
 *
 * Custom providers use credential keys of the form `"custom:<providerId>"`,
 * generated by Gate when the user configures a new endpoint. Gate is
 * responsible for storage and retrieval under these keys.
 *
 * Same open-union idiom as `ModelId`: named members get autocomplete;
 * arbitrary strings are accepted for custom provider keys.
 */
export type CredentialKey = BuiltInCredentialKey | (string & {});

export type ExportFormat = 'markdown' | 'html';

// ─── Token usage ──────────────────────────────────────────────────────────────

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  /** Estimated cost in USD, computed by Atlas at stream completion using Gate's pricing table. Absent when pricing data is unavailable for the model. */
  estimatedCost?: number;
}

/**
 * Running session totals for a single model. Aria reads this to display
 * per-model usage in the UI (issue #15 / #16).
 *
 * Defined as a `TokenUsage` intersection to eliminate field duplication (#144).
 * The shape is structurally identical to the previous explicit definition —
 * all existing object literals `{ modelId, inputTokens, outputTokens, totalTokens }`
 * continue to satisfy this type without modification.
 */
export type SessionTokenUsage = { modelId: ModelId } & TokenUsage;

// ─── Attachments ──────────────────────────────────────────────────────────────

/**
 * A single file attachment on a user message. Phase 5 (issue #285).
 *
 * Only image MIME types are supported in the initial implementation. The union
 * is intentionally closed to the four types every vision-capable provider
 * accepts. Extending to other file types (PDF, etc.) requires a types PR when
 * a provider adds explicit support for them.
 *
 * `base64` is the raw base64-encoded file content — no data-URL prefix
 * (i.e. no "data:image/jpeg;base64," preamble). Atlas prepends the appropriate
 * prefix when constructing provider-specific content parts.
 *
 * `sizeBytes` is the unencoded file size in bytes. Aria enforces a
 * per-attachment size ceiling before adding to the pending message; Atlas reads
 * this field for telemetry.
 *
 * `filename` is optional — clipboard pastes carry no filename; file-picker
 * selections always carry one.
 *
 * Lifecycle:
 *   - Aria creates `Attachment` objects from the file picker / clipboard-paste
 *     handler and attaches them to the pending user message before calling
 *     `sendMessage`.
 *   - Atlas reads attachments from `SendMessageOptions.attachments` (the
 *     current in-flight turn) and from `Message.attachments` on prior messages
 *     in `conversation.messages` (conversation history). Atlas must not pass
 *     attachment content to a provider whose `capabilities.vision` is `false`
 *     or absent — see `ProviderCapabilities.vision`.
 *   - Vault persists `Attachment` objects as part of `Conversation.messages`
 *     in localStorage; base64 content is stored verbatim. There is no separate
 *     blob store in Phase 5.
 */
export interface Attachment {
  id: string;
  mimeType: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';
  /** Raw base64-encoded content, without a data-URL prefix. */
  base64: string;
  /** Present when the attachment originated from the file picker; absent for clipboard pastes. */
  filename?: string;
  /** Unencoded file size in bytes. */
  sizeBytes: number;
}

// ─── Generated images — model-returned image content ──────────────────────────

/**
 * A single image returned by a model in its response. Phase 5 (issue #363).
 *
 * This represents image content that a model generates or returns — distinct
 * from `Attachment`, which represents images a user uploads with their message.
 * The directional difference is load-bearing: `Attachment` flows user → model
 * (input); `GeneratedImage` flows model → user (output).
 *
 * Structural consistency with `Attachment`:
 *   `base64` is the raw base64-encoded image content — no data-URL prefix
 *   (i.e. no "data:image/png;base64," preamble). This matches the convention
 *   established by `Attachment.base64`. Atlas must strip any data-URL prefix
 *   before populating this field; Aria prepends the appropriate prefix when
 *   rendering the image in an `<img>` element.
 *
 * `mimeType` is an open `string` rather than a closed union. Unlike user
 * attachments — where Roundtable controls which formats are accepted — the
 * provider controls which formats it returns. Using a closed union here would
 * require a types PR each time a provider adds a new output format.
 * Aria's `<img>` element accepts any browser-supported MIME type.
 *
 * `altText` is an optional model-supplied description. When present, Aria
 * uses it as the `alt` attribute on the rendered `<img>` element. When absent,
 * Aria must supply a meaningful fallback (e.g. "Generated image") to maintain
 * WCAG 2.1 AA compliance — never an empty `alt`.
 *
 * `width` and `height` are optional pixel dimensions as reported by the
 * provider. Aria uses these as `width` / `height` hints to prevent layout
 * shift while the image loads. When absent, Aria renders without explicit
 * dimensions.
 *
 * Lifecycle:
 *   - Atlas parses image content blocks from provider responses and creates
 *     `GeneratedImage` objects (issue #364). Atlas emits them via
 *     `StreamChunk.images` at stream completion.
 *   - Vault persists `GeneratedImage` objects as part of `Message.generatedImages`
 *     in localStorage; base64 content is stored verbatim (issue #365).
 *   - Aria reads `Message.generatedImages` and renders each image below the
 *     text content in assistant message bubbles (issue #366).
 */
export interface GeneratedImage {
  /** Stable identifier for this image, assigned by Atlas when parsing the response. */
  id: string;
  /** MIME type of the image, e.g. "image/png", "image/jpeg", "image/webp". Open string — not a closed union. */
  mimeType: string;
  /** Raw base64-encoded image content, without a data-URL prefix. */
  base64: string;
  /** Optional description provided by the model. Aria uses this as the img alt attribute. */
  altText?: string;
  /** Optional image width in pixels, as reported by the provider. */
  width?: number;
  /** Optional image height in pixels, as reported by the provider. */
  height?: number;
}

// ─── Messages ─────────────────────────────────────────────────────────────────

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  /** Present on assistant messages. */
  modelId?: ModelId;
  timestamp: number;
  /** Populated when isDone is true on the final StreamChunk. */
  tokenUsage?: TokenUsage;
  /** Phase 2 — directed replies. */
  targetModelId?: ModelId;
  /** True while the message is still streaming. */
  isStreaming?: boolean;
  /** Set on assistant messages when the stream terminated with an error. */
  error?: ModelError;
  /**
   * Attached files. Present only on user-role messages; always absent on
   * assistant-role messages. Atlas reads these when building multimodal
   * requests for vision-capable providers (Phase 5, issue #285).
   */
  attachments?: Attachment[];
  /**
   * Images returned by the model in this message. Present only on
   * assistant-role messages; always absent on user-role messages — users
   * send attachments (input), models return generated images (output).
   * Atlas populates this from provider response image content blocks
   * (issue #364). Vault persists this alongside the rest of the message
   * (issue #365). Aria renders each image below the text content in the
   * assistant bubble (issue #366).
   */
  generatedImages?: GeneratedImage[];
}

// ─── Model version selection ───────────────────────────────────────────────────

/**
 * A single selectable version of a model, surfaced in the model config panel.
 *
 * Atlas populates these on each ModelRegistryEntry. Aria renders them as a
 * version picker control inside the per-model settings panel. Gate persists the
 * user's selection via `selectedVersionId` on `ModelConfig`.
 *
 * `id` must be the exact API-level model string passed to the provider endpoint
 * (e.g. "claude-opus-4-5", "gpt-4o", "gemini-2.5-pro"). `displayName` is the
 * human-readable label shown in the picker. `description` is an optional
 * one-liner surfaced as a subtitle or tooltip.
 *
 * Design note: available versions are static (known at build time). This type
 * therefore lives on the MODEL_REGISTRY entry in Atlas, NOT on `ModelProvider`.
 * Adding `getAvailableVersions()` to `ModelProvider` would force every runtime
 * provider instance to carry static data it has no business owning, and would
 * complicate mocking in tests. If a future provider needs dynamic version
 * discovery (e.g. fetching from a versions endpoint), surface that as a
 * separate interface at that time — do not extend ModelProvider prematurely.
 */
export interface ModelVersionOption {
  /** API-level model string, e.g. "claude-opus-4-5", "gpt-4o". */
  id: string;
  /** Human-readable label shown in the version picker, e.g. "Claude Opus 4". */
  displayName: string;
  /** Optional one-liner shown as subtitle or tooltip, e.g. "Most capable". */
  description?: string;
}

// ─── Model config ─────────────────────────────────────────────────────────────

export interface ModelConfig {
  modelId: ModelId;
  /** Display name shown in UI. */
  name: string;
  /** Tailwind color token, e.g. "violet" or "sky". */
  color: string;
  /** Phase 2 — per-model system prompt. */
  systemPrompt?: string;
  isActive: boolean;
  /**
   * The `id` of the `ModelVersionOption` the user has selected for this model.
   * Absence means "use the provider's default version" (i.e. whatever Atlas
   * sends when no explicit model string override is applied).
   *
   * Gate reads and writes this field. Atlas reads it in `sendMessage` to choose
   * which API model string to pass to the provider endpoint. Aria reads it to
   * highlight the active option in the version picker.
   */
  selectedVersionId?: string;
}

// ─── Provider roster — Gate stores, Aria renders, Atlas dispatches ────────────

/**
 * Persisted configuration for a single built-in provider in the user's roster.
 *
 * Gate writes one of these per built-in provider the user has configured.
 * `isVisible` controls whether the provider appears in the Aria model selector
 * and can be added to new conversations — it does NOT remove the provider from
 * Atlas's dispatch table. A non-visible provider will simply never be active.
 *
 * `selectedVersionId` is the API-level model string the user last chose for
 * this provider (e.g. "claude-sonnet-4-6"). Absence means "use provider default".
 *
 * `credentialKey` is the `BuiltInCredentialKey` for the provider. Gate derives
 * this from `MODEL_CREDENTIAL_MAP` at write time so Atlas and Aria never need
 * to re-derive it.
 */
export interface BuiltInProviderConfig {
  kind: 'builtin';
  /** One of the six built-in model identifiers. */
  modelId: BuiltInModelId;
  /** The credential key used to retrieve the API key from Gate. */
  credentialKey: BuiltInCredentialKey;
  /**
   * The `id` of the `ModelCatalogEntry` the user has selected for this provider.
   * Absence means "use the provider's default version."
   */
  selectedVersionId?: string;
  /**
   * Whether this provider is visible in the Aria model selector.
   * Default: true. Users can set this to false to hide a built-in they do not use.
   */
  isVisible: boolean;
  /**
   * Declared feature capabilities of this built-in provider. Phase 5 (issue #285).
   *
   * Design decision — vision-capability cross-boundary resolution:
   *   Aria needs to show a pre-send warning modal when any active model lacks vision
   *   support ("Model X won't see your image"). Built-in capability defaults are
   *   authoritative in Atlas's domain, which Aria cannot import from. Rather than
   *   adding a runtime constant to this types file (which would violate the
   *   types-only rule) or having Aria maintain a second static copy, the solution
   *   is to add `capabilities` here — mirroring the existing field on
   *   `CustomProviderConfig` — and have Gate populate it from Gate's own static
   *   built-in capability map (following the BUILTIN_META precedent established
   *   in ProviderSettingsPanel). This gives Aria a uniform path to check
   *   `config.capabilities?.vision` for both built-in and custom providers without
   *   any cross-boundary import.
   *
   * Gate is responsible for writing this from its own BUILTIN_META-style capability
   * map when initializing or migrating the roster. Atlas also reads it — when
   * `vision` is `true`, Atlas may include image content parts; when `false` or
   * absent, Atlas must send text-only requests to this provider.
   *
   * When absent (pre-migration records), Aria and Atlas apply the conservative
   * `ProviderCapabilities` defaults: `vision: false`, `toolUse: false`.
   * Gate must ensure this is populated for all six built-ins on roster init/migration.
   *
   * @see ProviderCapabilities for field-by-field semantics and defaults.
   * @see CustomProviderConfig.capabilities for the analogous field on custom providers.
   */
  capabilities?: ProviderCapabilities;
}

/**
 * Declared feature capabilities of a custom OpenAI-compatible provider endpoint.
 *
 * Not all endpoints that speak the OpenAI Chat Completions wire format implement
 * the full API surface. Some reject `stream_options`, some lack system-role
 * support, some never expose vision or function calling. This interface lets the
 * user declare — at provider-configuration time — which features their endpoint
 * actually supports. Atlas reads these declarations at request-build time and
 * omits unsupported parameters rather than probing for failures at runtime.
 *
 * All fields are optional. Absence of a field means "Atlas uses its built-in
 * default for this capability" — Atlas owns and documents those defaults in
 * `/src/models/generic.ts`. Gate writes this object when the user configures or
 * updates a custom provider; Aria may expose capability toggles in the provider
 * settings panel.
 *
 * This is a pure static declaration — not a runtime cache. Once Atlas reads it
 * on a given request, no further probing occurs.
 *
 * Design constraint: all fields are optional so existing `CustomProviderConfig`
 * records that predate this field remain valid without migration.
 */
export interface ProviderCapabilities {
  /**
   * Whether the endpoint supports `stream_options: { include_usage: true }` in
   * streaming requests (OpenAI Chat Completions format).
   *
   * When `true` (or absent), Atlas includes `stream_options` to request token
   * counts in the final SSE chunk. When `false`, Atlas omits `stream_options`
   * entirely — no token counts are available for this provider session.
   *
   * Default (when absent): `true`. Optimistic — most conformant endpoints
   * support this, and the current try/retry Option B behavior already handles
   * the error case gracefully. Explicit `false` replaces that probe with a
   * static skip, eliminating the one extra failed request per session.
   */
  streamUsage?: boolean;

  /**
   * Whether the endpoint accepts multimodal image inputs (vision).
   *
   * When `true`, Atlas may include `image_url` content parts in the messages
   * array. When `false` (or absent), Atlas must send text-only content — passing
   * image parts to a non-vision endpoint produces an API error.
   *
   * Default (when absent): `false`. Conservative — vision is a strict superset
   * of text completion; most custom endpoints serve text-only models even when
   * the underlying inference server is vision-capable. Explicit `true` opts in.
   */
  vision?: boolean;

  /**
   * Whether the endpoint supports function calling / tools.
   *
   * When `true`, Atlas may include a `tools` array in the request body and
   * handle `tool_calls` in the response. When `false` (or absent), Atlas must
   * not send function definitions — endpoints that lack tool support return
   * errors or ignore the field silently.
   *
   * Default (when absent): `false`. Conservative — function calling is an
   * optional extension; many lightweight inference servers and proxied endpoints
   * do not implement it.
   */
  toolUse?: boolean;

  /**
   * Whether the endpoint accepts a `system`-role message.
   *
   * When `true` (or absent), Atlas prepends the system prompt as a `role:
   * "system"` message in the messages array, which is the standard OpenAI
   * behavior. When `false`, Atlas must fold the system prompt into the first
   * user message or omit it — some minimalist endpoints (certain Ollama
   * models, stripped-down inference servers) reject or silently drop system
   * messages.
   *
   * Default (when absent): `true`. Optimistic — system-role support is
   * specified in the OpenAI Chat Completions format and nearly universally
   * implemented by conformant endpoints.
   */
  systemPrompt?: boolean;
}

/**
 * Persisted configuration for a user-configured custom OpenAI-compatible provider.
 *
 * Gate writes one of these when the user adds a custom endpoint (OpenRouter,
 * Ollama, LM Studio, private endpoint, etc.). Atlas instantiates a dynamic
 * provider for each entry in the roster whose kind is 'custom'.
 *
 * `id` is a Gate-generated unique string (e.g. "custom-openrouter-1").
 * It serves as the `ModelId` for this provider everywhere in the system.
 * Gate must ensure no `id` collides with a `BuiltInModelId` value.
 *
 * `credentialKey` is Gate-generated and follows the pattern `"custom:<id>"`.
 * If the endpoint requires no authentication, `credentialKey` may be absent.
 *
 * `modelString` is the exact model identifier sent to the provider endpoint
 * (e.g. "meta-llama/llama-3-70b-instruct" for OpenRouter). This is distinct
 * from `id` — `id` identifies the provider config record; `modelString` is
 * the API parameter.
 *
 * `color` is an optional CSS custom-property token name (e.g. "accent-other")
 * or 6-digit hex string. Absence means Aria uses the 'accent-other' fallback.
 */
export interface CustomProviderConfig {
  kind: 'custom';
  /** Gate-generated unique identifier. This is the `ModelId` for this provider. */
  id: string;
  /** Human-readable label shown in the model selector and message bubbles. */
  displayName: string;
  /** Full URL of the OpenAI-compatible /chat/completions endpoint. */
  endpointUrl: string;
  /** Gate-generated credential key for this provider's API key (pattern: "custom:<id>"). */
  credentialKey?: string;
  /**
   * The model string sent to the provider endpoint (e.g. "llama-3-70b-instruct").
   * For providers like Ollama that use short names, this is exactly what they expect.
   */
  modelString: string;
  /**
   * Optional accent color. CSS custom-property token (e.g. "accent-other")
   * or 6-digit hex string (e.g. "#FF5500"). Aria applies 'accent-other' when absent.
   */
  color?: string;
  /**
   * Whether this provider requires an API key for authentication.
   *
   * When `false`, Gate skips the credential-present check before activating
   * the provider, and Atlas omits the `Authorization` header on all requests
   * to this provider's endpoint. Intended for no-auth providers such as Ollama
   * or other locally-hosted LLM servers that accept unauthenticated connections.
   *
   * When `true` or absent (the default), Gate enforces that a credential value
   * is stored for `credentialKey` before allowing the provider to be used.
   * Absence preserves existing behavior — all providers configured before this
   * field existed are treated as requiring a key.
   */
  requiresApiKey?: boolean;
  /**
   * Declared feature capabilities of this provider endpoint.
   *
   * Optional — absence means "no explicit overrides; Atlas uses its built-in
   * default for each capability." Gate writes this when the user configures or
   * later edits the provider. Atlas reads it at request-build time to decide
   * which parameters to include in the API call.
   *
   * Existing `CustomProviderConfig` records that predate this field are valid
   * without migration — Atlas falls back to per-capability defaults on every
   * field that is absent.
   *
   * @see ProviderCapabilities for field-by-field semantics and defaults.
   */
  capabilities?: ProviderCapabilities;
}

/**
 * A single entry in the user's provider roster.
 * Discriminated on `kind` — 'builtin' or 'custom'.
 */
export type ProviderConfig = BuiltInProviderConfig | CustomProviderConfig;

/**
 * The user's complete configured provider roster.
 *
 * Gate owns storage (localStorage key: "roundtable:provider-roster").
 * Aria reads it to populate the model selector and conversation model list.
 * Atlas reads it to resolve which providers to instantiate and dispatch to.
 *
 * Ordering: the array order is the display order in the Aria model selector.
 * Gate may allow the user to reorder entries; Atlas must respect the order when
 * building the active provider list for a conversation.
 *
 * An empty roster is valid — the user has configured no providers yet.
 * Aria should surface a "configure providers" onboarding prompt in this state.
 */
export type ProviderRoster = ProviderConfig[];

// ─── Model catalog — model version entries from any source ────────────────────

/**
 * Provenance of a `ModelCatalogEntry` — where the version information came from.
 *
 * - 'bundled'  — shipped with Roundtable at build time (Atlas's static registry)
 * - 'remote'   — fetched from a remote `models.json` at runtime (raw.githubusercontent.com)
 * - 'live-api' — discovered via a provider's live models endpoint (e.g. OpenRouter /api/v1/models)
 */
export type ModelCatalogSource = 'bundled' | 'remote' | 'live-api';

/**
 * Normalized shape for a single selectable model version, regardless of source.
 *
 * This is the richer replacement for `ModelVersionOption`. It carries the same
 * `id`, `displayName`, and `description` fields as `ModelVersionOption`, plus
 * `source` for provenance tracking and an optional `contextWindow` for display.
 *
 * Atlas uses this in its dynamic registry (replacing the static `ModelVersionOption[]`
 * on `ModelRegistryEntry`) when it fetches versions from remote sources.
 * Aria renders these in the version picker the same way it renders `ModelVersionOption`.
 * Gate persists the selected `id` via `selectedVersionId` on `ProviderConfig`.
 *
 * `id` must be the exact API-level model string passed to the provider endpoint
 * (e.g. "claude-opus-4-8", "meta-llama/llama-3-70b-instruct").
 *
 * Backward compat: `ModelVersionOption` is retained for Atlas's static built-in
 * registry. New code that handles dynamic version lists should use `ModelCatalogEntry`.
 * Aria's version picker accepts either type by reading only `id`, `displayName`, and
 * `description` — both shapes are structurally compatible with those three fields.
 */
export interface ModelCatalogEntry {
  /** API-level model string, e.g. "claude-opus-4-8", "meta-llama/llama-3-70b-instruct". */
  id: string;
  /** Human-readable label shown in the version picker, e.g. "Claude Opus 4". */
  displayName: string;
  /** Optional one-liner shown as subtitle or tooltip, e.g. "Most capable". */
  description?: string;
  /** Where this entry originated. */
  source: ModelCatalogSource;
  /** Optional context window size in tokens, shown in the version picker if present. */
  contextWindow?: number;
}

// ─── Conversation ─────────────────────────────────────────────────────────────

export interface Conversation {
  id: string;
  /** Auto-generated from the first user message. */
  title?: string;
  messages: Message[];
  models: ModelConfig[];
  interactionMode: InteractionMode;
  /** Ghost mode: nothing is ever written to storage. */
  isGhost: boolean;
  createdAt: number;
  updatedAt: number;
  /** Set when the conversation is archived. */
  archivedAt?: number;
  /** Phase 3 — group/folder assignment. */
  groupId?: string;
}

// ─── ConversationStore — consumed by Aria ────────────────────────────────────

/**
 * Read-only view of conversation state exposed to the UI layer.
 * Vault owns the implementation; Aria consumes it (e.g. via React context).
 */
export interface ConversationStore {
  conversations: Conversation[];
  activeConversationId: string | null;
  getConversation(id: string): Conversation | undefined;
  getActiveConversation(): Conversation | undefined;
  /**
   * Returns running session token totals for every active model in the given
   * conversation. Aria uses this for the per-model usage display (issue #15 / #16).
   * Atlas also exports a standalone getSessionTokenUsage() utility from
   * @/models for convenience (documented exception to the boundary rule).
   */
  getSessionTokenUsage(conversationId: string): SessionTokenUsage[];
}

// ─── ConversationContext — Atlas's narrowed view of a conversation ────────────

/**
 * The slice of `Conversation` that Atlas is authorized to read when handling
 * a `sendMessage` call. It excludes Vault-internal and display-only fields
 * (`isGhost`, `archivedAt`, `groupId`, `title`, `createdAt`, `updatedAt`,
 * `interactionMode`) that Atlas has no business inspecting.
 *
 * Atlas reads: `id` (for telemetry/logging), `messages` (conversation history),
 * and `models` (for `systemPrompt` and `selectedVersionId` per model).
 *
 * Structural note: `Conversation` is a strict superset of `ConversationContext`,
 * so existing callers that pass a full `Conversation` to `sendMessage` continue
 * to compile without changes — TypeScript structural typing satisfies the
 * narrower type automatically. The restriction is enforced at the type level
 * only; no runtime transformation is needed.
 *
 * Aria passes the full active `Conversation`; tests may pass a minimal object
 * that satisfies only the three required fields.
 */
export interface ConversationContext {
  id: string;
  messages: Message[];
  /** Atlas reads `systemPrompt` and `selectedVersionId` per model entry. */
  models: ModelConfig[];
}

// ─── Streaming — sendMessage plumbing ─────────────────────────────────────────

export interface StreamChunk {
  modelId: ModelId;
  /** Incremental text delta. */
  content: string;
  isDone: boolean;
  /** Present only when isDone is true. */
  tokenUsage?: TokenUsage;
  /**
   * Images returned by the model in this chunk. Typically populated only on
   * the final chunk (when `isDone` is true), since providers return image
   * content blocks as complete units rather than incrementally.
   * Atlas emits this when parsing image content blocks from the provider
   * response (issue #364). Aria accumulates these across chunks and writes
   * the complete array to `Message.generatedImages` on stream completion.
   */
  images?: GeneratedImage[];
  error?: ModelError;
}

export type StreamHandler = (chunk: StreamChunk) => void;

// ─── sendMessage — Atlas exposes, Aria calls ──────────────────────────────────

export interface SendMessageOptions {
  conversationId: string;
  content: string;
  /** Phase 2 — omit to broadcast to all active models. */
  targetModelId?: ModelId;
  /** Phase 2 — omit for parallel/manual modes. Atlas uses this to sequence auto-chain calls. */
  chainConfig?: AutoChainConfig;
  /**
   * A narrowed view of the active conversation. Atlas reads `id`, `messages`,
   * and `models` (for `systemPrompt` and `selectedVersionId` per model). Vault-
   * internal and display-only fields (`isGhost`, `archivedAt`, `groupId`,
   * `title`, `createdAt`, `updatedAt`, `interactionMode`) are excluded from
   * this type — Atlas must not depend on them.
   *
   * When absent, Atlas falls back to the static PROVIDERS registry with no
   * per-model config resolution — a legacy/test path that remains valid.
   *
   * Aria should always pass the active conversation here. Absence is permitted
   * only for callers (e.g. tests) that intentionally bypass roster resolution.
   *
   * Structural compat: `Conversation` satisfies `ConversationContext`, so
   * existing callers passing a full `Conversation` continue to compile without
   * changes.
   */
  conversation?: ConversationContext;
  /**
   * Shared system prompt applied to all models in parallel/directed/auto-chain mode.
   *
   * When a model also has a `systemPrompt` set on its `ModelConfig` entry in
   * `conversation.models`, the per-model value takes precedence over this shared
   * value. Use this field when a single prompt should apply across all active
   * models and no per-model override is configured.
   *
   * Omit (or pass `undefined`) to use each model's own configured system prompt,
   * or no system prompt at all when no per-model value is set.
   */
  systemPrompt?: string;
  /**
   * Optional cancellation signal for the fan-out. When aborted, Atlas should
   * terminate all active provider streams as quickly as possible.
   *
   * Design note: this field lives on `SendMessageOptions` rather than on
   * `ModelProvider.sendMessage` because every concrete provider already uses
   * the fourth positional parameter slot for `selectedVersionId?: string`
   * (an Atlas-internal version-threading mechanism). Adding `signal` as a
   * fourth parameter on the public interface would make all six provider
   * implementations structurally incompatible with `ModelProvider`. Atlas
   * extracts this signal from `options` and threads it to individual providers
   * through its internal `VersionAwareProvider` type, which Atlas owns and may
   * extend freely.
   *
   * Aria passes this by creating an `AbortController`, storing the controller
   * as state, and passing `controller.signal` here. Aria calls `stopMessage()`
   * (which invokes `controller.abort()`) when the user clicks the stop button.
   */
  signal?: AbortSignal;
  /**
   * Files attached to the current in-flight user message. Phase 5 (issue #285).
   *
   * Atlas reads these to build multimodal content parts for vision-capable
   * providers. Providers whose `capabilities.vision` is `false` or absent must
   * not receive attachment content — Atlas is responsible for filtering per
   * provider before building the request payload.
   *
   * Note: these are the attachments on the current turn only. Prior user
   * messages that carried attachments are already stored in
   * `conversation.messages` under `Message.attachments` and will be included
   * naturally in the history Atlas sends to the provider (subject to the same
   * per-provider vision capability check).
   *
   * Aria creates `Attachment` objects from the file picker / paste handler and
   * passes them here alongside `content`. Absence means no attachments on this
   * turn — text-only message.
   */
  attachments?: Attachment[];
}

/**
 * Top-level send function. Fans out to all active ModelProviders in parallel.
 * Streams each model's response via onChunk. Resolves when all models are done.
 */
export type SendMessageFn = (
  options: SendMessageOptions,
  onChunk: StreamHandler
) => Promise<void>;

/**
 * Aborts all active streams for the current fan-out.
 *
 * Atlas implements this by signalling the AbortController(s) it created when
 * the paired `sendMessage` call was dispatched. Aria wires this to a stop
 * button in the input bar.
 *
 * Atlas provides a no-op stub before any stream is in flight; the real
 * implementation is installed at the moment `sendMessage` begins dispatching.
 * Calling `stopMessage` after all streams have already settled is safe and has
 * no effect.
 *
 * Aria: import this type and add `stopMessage: StopMessageFn` to
 * `RoundtableContextValue` so the stop button can call it.
 */
export type StopMessageFn = () => void;

// ─── ModelProvider — Atlas implements per model ───────────────────────────────

export type ModelErrorCode =
  | 'auth_failure'
  | 'rate_limit'
  | 'network_error'
  | 'context_length_exceeded'
  | 'unknown';

/**
 * Common base for all Roundtable error types. Aria uses this to write a
 * unified error boundary that catches `ModelError`, `StorageError`, and
 * `BackendAuthError` without separate catch branches.
 *
 * `source` is the discriminant — narrow to a concrete subtype using it:
 *   `if (err.source === 'model') { ... ModelError fields ... }`
 *
 * `code` is typed as `string` here to accommodate the different `code` unions
 * on each subtype. Concrete subtypes narrow `code` to their specific union.
 * `message` is the human-readable description of the error.
 */
export interface AppError {
  code: string;
  message: string;
  /**
   * Discriminant identifying which layer produced the error. Optional on the
   * base to remain backward-compatible with existing `ModelError` object
   * literals in Atlas that predate this unified type — those omit `source`
   * and are still valid `ModelError` values. New error construction sites
   * must always set `source`. Aria narrows on this field when present:
   * `if (err.source === 'model') { ... }`
   */
  source?: 'model' | 'storage' | 'auth';
}

/**
 * Error emitted by Atlas when a model call fails. The `modelId` field
 * identifies which model failed — relevant in parallel-broadcast mode where
 * one model's failure must not prevent others from continuing.
 *
 * Extends `AppError` with `source: 'model'` as the discriminant.
 */
export interface ModelError extends AppError {
  /**
   * Optional for backward compatibility with existing Atlas construction sites
   * that omit `source`. New code must always set `source: 'model'`. Aria
   * discriminates on this field when present.
   */
  source?: 'model';
  code: ModelErrorCode;
  message: string;
  /** Present when the error is attributable to a specific model. */
  modelId?: ModelId;
}

/**
 * Error emitted by Vault when a storage operation fails.
 *
 * Extends `AppError` with `source: 'storage'` as the discriminant.
 *
 *   - `quota_exceeded` — localStorage quota exhausted (QuotaExceededError)
 *   - `parse_failure`  — stored data present but corrupt (JSON.parse failure)
 *   - `not_found`      — requested conversation ID does not exist
 *   - `unknown`        — any other storage-layer error
 */
export interface StorageError extends AppError {
  source: 'storage';
  code: 'quota_exceeded' | 'parse_failure' | 'not_found' | 'unknown';
}

/**
 * Error emitted by Gate when an API key operation fails.
 *
 * Extends `AppError` with `source: 'auth'` as the discriminant.
 *
 *   - `invalid_key`  — key present in localStorage but rejected by the provider
 *   - `missing_key`  — no key stored for the requested credential
 *   - `expired_key`  — key was valid but has since expired (provider-reported)
 *   - `unknown`      — any other auth-layer error
 */
export interface BackendAuthError extends AppError {
  source: 'auth';
  code: 'invalid_key' | 'missing_key' | 'expired_key' | 'unknown';
}

export interface ModelProviderConfig {
  modelId: ModelId;
  name: string;
  color: string;
  /** The CredentialKey used to fetch the API key from Gate. */
  credentialKey: CredentialKey;
}

export interface ModelProvider {
  readonly config: ModelProviderConfig;
  /**
   * Sends messages to the underlying model and streams the response.
   * Resolves with token usage once the stream is complete.
   * Rejects if a non-recoverable error occurs (auth, network, etc.).
   *
   * Cancellation: stream cancellation is not surfaced as a parameter here
   * because all concrete providers already use the fourth positional slot
   * for `selectedVersionId` (an Atlas-internal concern). Atlas threads the
   * `AbortSignal` from `SendMessageOptions.signal` to individual providers
   * via its internal `VersionAwareProvider` type.
   */
  sendMessage(
    messages: Message[],
    systemPrompt: string | undefined,
    onChunk: StreamHandler
  ): Promise<{ tokenUsage?: TokenUsage }>;
}

// ─── Conversation defaults — Vault stores, Aria consumes ─────────────────────

/**
 * The defaults applied when initializing a new conversation.
 *
 * Vault persists this under localStorage key "roundtable:conversation-defaults".
 * Vault writes it at the end of every conversation session by calling
 * `saveConversationDefaults`. Aria reads it via `getConversationDefaults` when
 * initializing a new conversation — if present, pre-populates the active model
 * roster and interaction mode with the last-used values. If absent (first run
 * or storage cleared), Aria applies its own hardcoded fallback defaults.
 *
 * Ghost-mode state (`isGhost`) is intentionally excluded — ghost mode is a
 * per-session opt-in and must never persist across conversation boundaries.
 */
export interface ConversationDefaults {
  /**
   * The model IDs that were active at the end of the last conversation.
   * Aria uses this to pre-populate the model roster on new conversation init.
   *
   * Empty array is valid — the user had no active models. Aria treats this as
   * "show the model-selector onboarding prompt" rather than initializing with
   * a roster of zero models. Aria must not infer "missing defaults" from an
   * empty array — an empty array is a legitimate stored state.
   */
  activeModelIds: ModelId[];
  /**
   * The interaction mode active at the end of the last conversation.
   * Aria uses this to pre-select the mode switcher control on new conversation init.
   */
  interactionMode: InteractionMode;
}

/**
 * Retrieve the stored conversation defaults.
 *
 * Returns `null` when no defaults have been saved yet (first run, storage
 * cleared) and when the stored value is corrupt (parse failure). Callers must
 * treat `null` as "no defaults available" — Aria applies its own hardcoded
 * fallback defaults in that case.
 *
 * Does not throw. Vault stores this under localStorage key
 * "roundtable:conversation-defaults".
 *
 * Vault implements; Aria calls this on new conversation init before constructing
 * the initial model roster and mode switcher state.
 */
export type GetConversationDefaultsFn = () => Promise<ConversationDefaults | null>;

/**
 * Persist conversation defaults for use when initializing the next new
 * conversation.
 *
 * Vault implements; Aria calls this when leaving a conversation — specifically
 * when the user creates a new conversation or when the page is about to unload —
 * passing the active model IDs and current interaction mode from the conversation
 * being left.
 *
 * Ghost-mode guard: Aria must NOT call this when leaving a ghost conversation.
 * Ghost state must never propagate into stored defaults. The guard belongs in
 * Aria because `ConversationDefaults` carries no `isGhost` field from which
 * Vault could detect it.
 *
 * Vault stores this under localStorage key "roundtable:conversation-defaults".
 * Throws if the storage backend is full (QuotaExceededError). Aria should handle
 * this gracefully — failure to save defaults is non-fatal.
 */
export type SaveConversationDefaultsFn = (defaults: ConversationDefaults) => Promise<void>;

// ─── StorageProvider — Vault implements ───────────────────────────────────────

/**
 * Serialized content produced by converting a conversation to a given format.
 * The caller decides what to do with it — trigger a download, stream over HTTP,
 * write to disk, etc.
 */
export interface ExportedConversation {
  /** The serialized conversation body (UTF-8 string). */
  content: string;
  /** Suggested filename including extension, e.g. "my-chat.md". */
  filename: string;
  /** MIME type of the content, e.g. "text/markdown;charset=utf-8". */
  mimeType: string;
}

/**
 * Core persistence contract. Vault owns the implementation; all other agents
 * interact with storage exclusively through this interface.
 *
 * Design invariants:
 *   - All methods are async. localStorage is synchronous under the hood, but
 *     the async boundary is load-bearing: it allows a future ServerStorageProvider
 *     to substitute without interface changes.
 *   - Ghost-mode guard: `saveConversation` silently no-ops when
 *     `conversation.isGhost === true`. All other write methods are not
 *     ghost-aware — callers must never pass a ghost conversation ID to them.
 *   - Upsert semantics: `saveConversation` creates or fully replaces a record.
 *     To update a single field (e.g. `groupId`), load the conversation, mutate
 *     the local copy, and call `saveConversation` with the full updated object.
 *     There is no `patchConversation`.
 *   - Idempotent deletes: `deleteConversation` on a non-existent ID is a no-op.
 *   - Export is side-effect-free: `exportConversation` returns serialized content
 *     and does NOT trigger a browser download. Download is a DOM concern that a
 *     ServerStorageProvider cannot fulfill. Vault's LocalStorageProvider wraps
 *     the return value in a download trigger; other consumers may stream it,
 *     write it to disk, or return it over HTTP.
 */
export interface StorageProvider {
  /**
   * Persist a conversation (create or replace — upsert semantics).
   *
   * Ghost-mode guard: if `conversation.isGhost === true`, returns immediately
   * without writing anything. This is the canonical guard point — callers do
   * not need to check `isGhost` before calling.
   *
   * Throws if the storage backend is full (e.g. QuotaExceededError in
   * localStorage). The caller is responsible for surfacing this to the user.
   */
  saveConversation(conversation: Conversation): Promise<void>;

  /**
   * Load a single conversation by ID.
   *
   * Returns `null` if no record exists for the given ID, or if the stored
   * data is present but corrupt (parse failure). Does not throw on missing or
   * corrupt data — callers should treat `null` as "not found".
   */
  loadConversation(id: string): Promise<Conversation | null>;

  /**
   * Return all stored conversations, sorted newest-first by `updatedAt`.
   *
   * Conversations whose underlying data is corrupt or missing are silently
   * omitted so the list remains usable even when storage is partially damaged.
   * Archived conversations (those with `archivedAt` set) are included —
   * filtering by archive status is the UI's responsibility.
   * Ghost conversations are never included (they are not persisted).
   */
  listConversations(): Promise<Conversation[]>;

  /**
   * Permanently remove a conversation from storage.
   *
   * No-op if the conversation does not exist. Removes the record from both
   * the index and its data key. Does not cascade to any related records.
   */
  deleteConversation(id: string): Promise<void>;

  /**
   * Mark a conversation as archived by setting its `archivedAt` timestamp.
   *
   * No-op if the conversation does not exist. Archived conversations remain
   * in the index and are returned by `listConversations` — they are not
   * deleted. The UI is responsible for showing/hiding archived conversations.
   * Group membership (`groupId`) is preserved on archive.
   *
   * To reverse, call `unarchiveConversation`.
   */
  archiveConversation(id: string): Promise<void>;

  /**
   * Clear the `archivedAt` timestamp on a conversation, returning it to
   * active status.
   *
   * No-op if the conversation does not exist or was not archived.
   */
  unarchiveConversation(id: string): Promise<void>;

  /**
   * Serialize a conversation to the requested format and return the result.
   *
   * Returns `null` if the conversation does not exist.
   *
   * Side-effect-free: does NOT trigger a browser download. The caller decides
   * what to do with the content — Vault's LocalStorageProvider wraps this in a
   * download trigger; a ServerStorageProvider would stream it over HTTP.
   * The `filename` and `mimeType` fields are hints that callers may override.
   */
  exportConversation(id: string, format: ExportFormat): Promise<ExportedConversation | null>;
}

// ─── Themes ───────────────────────────────────────────────────────────────────

export type ThemeId = 'slate' | 'linen' | 'midnight' | 'ash' | 'ember' | 'chalk' | 'outrun';

/** Full token schema for a Roundtable theme. All fields required. */
export interface CustomThemeJSON {
  name: string;
  mode: 'dark' | 'light';
  surfaces: {
    background: string;
    card: string;
    sidebar: string;
    input: string;
  };
  text: {
    primary: string;
    secondary: string;
    muted: string;
    inverse: string;
  };
  borders: {
    default: string;
    subtle: string;
    strong: string;
  };
  accents: {
    'model-claude': string;
    'model-gpt': string;
    'model-gemini': string;
    'model-other': string;
    'model-grok': string;
    'model-deepseek': string;
    'model-mistral': string;
  };
  interactive: {
    hover: string;
    active: string;
    focusRing: string;
  };
  semantic: {
    success: string;
    warning: string;
    /** Foreground text color for error states (bright red, reads on dark surfaces). */
    error: string;
    /** Background color for destructive buttons (dark red, supports white text at 4.5:1+). */
    'error-bg': string;
    info: string;
  };
  radius: {
    sm: string;
    md: string;
    lg: string;
    full: string;
  };
  spacing: {
    '1': string;
    '2': string;
    '3': string;
    '4': string;
    '6': string;
    '8': string;
    '12': string;
    '16': string;
  };
  shadow: {
    none: 'none';
    sm: string;
    md: string;
    lg: string;
  };
  timing: {
    instant: string;
    fast: string;
    medium: string;
    slow: string;
  };
  /**
   * Prose typography colors. Applied as CSS custom properties by `applyTheme()`
   * in `/src/ui/theme.ts`. All 7 fields are required — Gate's `validateCustomTheme`
   * is fail-closed and rejects any custom theme JSON missing any of these.
   *
   * CSS variable mapping:
   *   code-bg            → --prose-code-bg
   *   code-border        → --prose-code-border
   *   code-text          → --prose-code-text
   *   block-bg           → --prose-block-bg
   *   link               → --prose-link
   *   link-hover         → --prose-link-hover
   *   blockquote-border  → --prose-blockquote-border
   *
   * Aria reads all 7 fields when rendering markdown prose content.
   * Gate validates all 7 fields as required 6-digit hex strings.
   * All built-in themes must supply all 7 values.
   */
  prose: {
    'code-bg': string;
    'code-border': string;
    'code-text': string;
    'block-bg': string;
    link: string;
    'link-hover': string;
    'blockquote-border': string;
  };
}

export interface ThemePreferences {
  activeThemeId: ThemeId;
  customTheme?: CustomThemeJSON;
}

/**
 * Identifies the currently active theme and its origin.
 *
 * `name` is the display name of the active theme:
 *   - For built-in themes: the human-readable label (e.g. "Slate", "Outrun").
 *   - For custom themes: the value of `CustomThemeJSON.name` as supplied by
 *     the user in their uploaded theme file.
 *
 * `source` discriminates the theme's origin:
 *   - 'builtin'  — one of the 7 `ThemeId` themes shipped with Roundtable.
 *   - 'custom'   — a user-uploaded `CustomThemeJSON` currently in
 *                  `ThemePreferences.customTheme`.
 *
 * Aria uses this in the theme import UI (#169) to show which theme is active
 * and label the "Replace with imported theme" confirmation flow. Gate computes
 * this from the current `ThemePreferences` at read time — it is never persisted
 * separately.
 *
 * Note: there is no separate `ThemeJSON` alias. `CustomThemeJSON` is the sole
 * type for the full validated theme JSON shape. This type (`ActiveTheme`) is
 * metadata about which theme is in use, not a container for the token values.
 */
export interface ActiveTheme {
  name: string;
  source: 'builtin' | 'custom';
}

// ─── Credentials — Gate implements ───────────────────────────────────────────

/**
 * Retrieve a stored API key. Returns undefined if not set.
 */
export type GetCredentialsFn = (key: CredentialKey) => string | undefined;

/**
 * Persist an API key to localStorage. Never transmit, log, or export keys.
 */
export type SaveCredentialsFn = (key: CredentialKey, value: string) => void;

/**
 * Remove a stored API key.
 */
export type ClearCredentialsFn = (key: CredentialKey) => void;

// ─── User preferences — Gate implements, Aria consumes ───────────────────────

/**
 * Controls when per-message token counts are visible in the chat UI.
 *
 * - 'always' — token counts shown unconditionally on all completed model bubbles
 * - 'active' — hover reveals on desktop, tap reveals on mobile (default;
 *              matches the hover-reveal behavior shipped in #16)
 * - 'never'  — token count element removed from DOM entirely (not hidden with CSS)
 *
 * Gate reads and writes this value; Aria reads it to determine render behavior.
 */
export type TokenCountVisibility = 'always' | 'active' | 'never';

/**
 * Persistent user preferences. Gate owns storage (localStorage); Aria reads
 * these values to drive conditional rendering and display behavior.
 *
 * Default values when no preference is stored:
 *   tokenCountVisibility: 'active'
 */
export interface UserPreferences {
  tokenCountVisibility: TokenCountVisibility;
}

// ─── Model accent color overrides — Gate implements, Aria consumes ────────────

/**
 * User-chosen accent colors that override the active theme's accent tokens.
 * Partial record — only models with active overrides are present.
 * Absence of a key means "use the active theme's default accent for that model."
 * Values are 6-digit hex strings (e.g. "#FF5500").
 *
 * Persisted by Gate under the localStorage key "roundtable:model-accent-colors".
 * Applied by Aria as a second CSS custom-property pass after the theme loader
 * runs — overriding `--accent-{model}` only for models present in this record.
 */
export type ModelAccentColors = Partial<Record<ModelId, string>>;

/**
 * Retrieve all stored model accent color overrides.
 * Returns {} when no overrides are stored or if the stored value is corrupt.
 * Gate implements; Aria calls this on app load and after every theme switch.
 */
export type GetModelAccentColorsFn = () => ModelAccentColors;

/**
 * Persist a single model accent color override.
 * Gate validates the hex value matches /^#[0-9A-Fa-f]{6}$/ before writing.
 * Throws TypeError on invalid hex — Aria must validate before calling.
 * Gate implements; Aria calls this when the user confirms a color selection.
 */
export type SetModelAccentColorFn = (modelId: ModelId, hex: string) => void;

/**
 * Remove the stored accent color override for a single model.
 * No-op if the model has no stored override.
 * Gate implements; Aria calls this when the user clicks "Reset to theme default"
 * in the color picker popover for a specific model.
 */
export type ClearModelAccentColorFn = (modelId: ModelId) => void;

/**
 * Remove all stored model accent color overrides.
 * Removes the entire "roundtable:model-accent-colors" localStorage key.
 * Gate implements; Aria calls this from the "Reset all model colors to theme
 * defaults" control in the Settings panel.
 */
export type ClearAllModelAccentColorsFn = () => void;

// ─── Setup export / import — Gate implements, Aria consumes ──────────────────

/**
 * Payload written to the cross-device setup transfer file (issue #305).
 *
 * Gate produces this object when the user triggers "Export setup". Gate
 * consumes it when the user triggers "Import setup". Aria initiates both
 * operations and receives `ImportResult` from the import path.
 *
 * `schemaVersion` must be incremented (via a types PR) when the shape changes
 * in a backward-incompatible way. Gate must reject payloads whose
 * `schemaVersion` exceeds the version it was built against.
 *
 * `exportedAt` is an ISO 8601 timestamp string (e.g. "2026-07-01T12:00:00.000Z").
 * Gate records this at export time so the import UI can display when the file
 * was created.
 *
 * `credentials` maps each `CredentialKey` to its stored plaintext value. Gate
 * reads from localStorage at export time and writes back at import time. The
 * export file itself is the secret — Gate must never transmit or log these values.
 *
 * `customProviders` is the complete array of user-configured custom OpenAI-
 * compatible providers at export time. Gate writes the full `CustomProviderConfig`
 * objects so the import side can reconstruct the provider roster exactly.
 *
 * `preferences` captures Gate-owned preferences (active theme, sidebar state,
 * etc.) as a loosely-typed record so the export format remains stable across
 * preference schema changes. Gate is responsible for interpreting these values
 * at import time and discarding any keys it does not recognize.
 */
export interface SetupExport {
  /** Schema version of this payload. Current value: 1. */
  schemaVersion: number;
  /** ISO 8601 timestamp recorded at export time, e.g. "2026-07-01T12:00:00.000Z". */
  exportedAt: string;
  /**
   * API credentials keyed by CredentialKey. Values are plaintext.
   * The export file is the secret — Gate must never transmit or log these values.
   */
  credentials: Record<string, string>;
  /** Full array of user-configured custom provider records at export time. */
  customProviders: CustomProviderConfig[];
  /**
   * Gate-owned preferences: active theme, sidebar state, etc.
   * Loosely typed so the export format remains stable across preference schema
   * changes. Gate discards unrecognized keys at import time.
   */
  preferences: Record<string, unknown>;
}

/**
 * Result returned by Gate's `importSetup()` after applying a `SetupExport` payload.
 *
 * `ok` is `true` when all import operations completed without error —
 * credentials written, custom providers registered, preferences applied.
 * Aria uses this to decide whether to show a success or partial-failure state
 * in the import UI.
 *
 * `errors` is always present and always an array. It is empty when `ok` is
 * `true`. When `ok` is `false`, each element is a human-readable description
 * of one failure or skipped operation. Aria renders these to the user so they
 * can diagnose partial import failures.
 */
export interface ImportResult {
  /** True when all import operations completed without error. */
  ok: boolean;
  /** Human-readable error descriptions. Empty array when ok is true. */
  errors: string[];
}

// ─── Proxy config — Gate implements, Atlas and Aria consume ──────────────────

/**
 * Runtime proxy configuration. When present, Atlas routes all provider API calls
 * through the specified proxy base URL instead of contacting the provider endpoint
 * directly.
 *
 * Use case: static deployments (e.g. GitHub Pages) where direct browser-to-provider
 * API calls are blocked by CORS. The user configures a Cloudflare Workers proxy URL;
 * all provider traffic flows through it, and the proxy forwards requests to the real
 * provider endpoint server-side where CORS does not apply.
 *
 * Gate owns storage (localStorage key: "roundtable:proxy-config").
 * Aria reads this to populate the proxy settings UI and to pass to the save/clear
 * functions when the user updates the proxy URL.
 * Atlas reads this at call time via `getProxyConfig()` to determine the effective
 * API base URL for every provider request.
 *
 * Cross-agent import exception: Atlas model files may import `getProxyConfig()`
 * from `@/auth` directly to read the proxy URL at call time. This follows the same
 * rationale as Aria importing `getProviderRoster()` — a pure read of a Gate-owned
 * setting that Atlas needs at the dispatch boundary. Any Atlas module that does so
 * must document the exception with a comment at the import site, per the pattern
 * established in `InputBar.tsx` and `App.tsx`.
 */
export interface ProxyConfig {
  /** Base URL of the user's proxy, e.g. "https://my-proxy.workers.dev". */
  url: string;
}

/** Gate implements. Aria and Atlas call this to read the runtime proxy URL. Returns null when no proxy is configured. */
export type GetProxyConfigFn = () => ProxyConfig | null;

/** Gate implements. Aria calls this when the user saves a proxy URL. */
export type SaveProxyConfigFn = (config: ProxyConfig) => void;

/** Gate implements. Aria calls this when the user clears the proxy URL. */
export type ClearProxyConfigFn = () => void;

// ─── Pricing — Gate implements, Atlas and Aria consume ────────────────────────

/**
 * Pricing for a single model variant in USD per 1 million tokens.
 *
 * Atlas reads this at send time to compute per-message cost:
 *   cost = (inputPer1M × inputTokens / 1_000_000) + (outputPer1M × outputTokens / 1_000_000)
 *
 * Gate writes this as values in `PricingTable` when populating from the
 * pricing JSON payload it fetches or loads from the bundled fallback.
 */
export interface PricingEntry {
  /** Input token price in USD per 1 million tokens. */
  inputPer1M: number;
  /** Output token price in USD per 1 million tokens. */
  outputPer1M: number;
}

/**
 * Full pricing dataset keyed by API model string.
 *
 * Keys are the exact API-level model strings sent to provider endpoints
 * (e.g. "claude-sonnet-4-6", "gpt-4o", "gemini-2.5-pro") — NOT `ModelId`
 * values. This distinction is intentional: pricing is version-specific,
 * and a single `ModelId` (e.g. "claude") may map to multiple versioned API
 * strings with different prices depending on which version the user has selected.
 *
 * Gate stores this in localStorage (key: "roundtable:pricing-table") and
 * exposes it via `GetPricingTableFn`. Atlas reads it at send time by looking up
 * the resolved API model string for the current request. Aria does not consume
 * `PricingTable` directly — it reads `PricingMetadata` for the staleness footer.
 *
 * Absence of a key means no pricing data is available for that model variant.
 * Atlas must treat a missing entry as "cost unknown" and omit cost display for
 * that model rather than blocking the send.
 */
export type PricingTable = Record<string, PricingEntry>;

/**
 * Freshness metadata for the pricing data currently in storage.
 *
 * Gate writes this alongside `PricingTable` whenever it performs a fetch or
 * falls back to the bundled pricing data. Aria reads it via `GetPricingMetadataFn`
 * to determine whether to render a staleness notice in `SessionTokenSection`.
 *
 * `lastFetched` is `null` when pricing has never been successfully fetched from
 * the remote source — the app is running entirely on bundled fallback data and
 * no prior fetch has ever succeeded.
 *
 * `source` discriminates how the current `PricingTable` was populated:
 *   - 'remote'   — the table reflects a successful network fetch
 *   - 'fallback' — the table reflects bundled data shipped with the build
 *                  (either because no fetch has ever succeeded, or because
 *                  the last fetch failed and the fallback was restored)
 */
export interface PricingMetadata {
  /** ISO timestamp of the last successful remote fetch, or null if never fetched. */
  lastFetched: string | null;
  /** Whether prices came from a successful network fetch or from the bundled fallback. */
  source: 'remote' | 'fallback';
}

/**
 * Runtime pricing configuration. Gate resolves the effective URL from:
 *   localStorage override → VITE_PRICING_URL env var → canonical default URL
 *
 * Gate uses this at fetch time to determine where to retrieve the pricing JSON.
 * Aria may expose a settings field for the localStorage override (issue #353).
 * This type carries the already-resolved URL; resolution logic lives in Gate.
 */
export interface PricingConfig {
  /** Fully resolved pricing JSON URL. Gate resolves: localStorage override → VITE env var → canonical default. */
  url: string;
}

/** Gate implements. Atlas and Aria call this to read the current pricing table. Returns null when no pricing data has been written yet. */
export type GetPricingTableFn = () => PricingTable | null;

/** Gate implements. Aria calls this to read pricing staleness metadata. Returns null when metadata has not been written yet. */
export type GetPricingMetadataFn = () => PricingMetadata | null;
