/**
 * Atlas — generic.ts
 *
 * GenericOpenAIProvider — a ModelProvider implementation that targets any
 * OpenAI-compatible streaming endpoint (OpenRouter, Ollama, LM Studio,
 * private endpoints, etc.).
 *
 * The endpoint URL, model string, and credential key all come from a
 * CustomProviderConfig supplied at construction time. SSE parsing is
 * identical to GPT55ModelProvider (OpenAI Chat Completions format).
 *
 * Security rules (non-negotiable):
 *   - The API key is retrieved at call-time via getCredentialsFn() and never stored in state
 *   - The API key is NEVER logged
 *   - The API key is only transmitted to the endpoint URL supplied by the user's config
 *
 * Credential injection: getCredentialsFn is passed in at construction time
 * (dependency injection) rather than imported from @/auth. This keeps @/models
 * free of cross-boundary imports. sendMessage.ts — which already imports from
 * @/auth for getProviderRoster — passes Gate's getCredentials here.
 *
 * Per-model token limit override (issue #493): when CustomProviderConfig.maxTokens
 * is set, it overrides MAX_TOKENS_GENERIC as the max_tokens value in the API request
 * body. Ollama models with 2k context windows can set maxTokens: 2048 to avoid errors;
 * 128k-context models can set a higher value to unlock their full output capacity.
 * When maxTokens is absent, MAX_TOKENS_GENERIC (8192) remains the fallback.
 *
 * Image generation (issues #376, #379):
 *   When CustomProviderConfig.capabilities.imageGeneration === true AND the caller
 *   passes requestImageGeneration === true, this provider includes
 *   modalities: ["image", "text"] in the request body. OpenRouter returns generated
 *   images in choices[].delta.images[] on the streaming chunks. This provider
 *   collects those images and emits them via StreamChunk.images on the final done chunk.
 *
 *   Opt-in gate: BOTH conditions must be true to enable image gen:
 *     1. capabilities.imageGeneration === true on the provider config (static capability)
 *     2. requestImageGeneration === true passed at call time (user's per-message toggle,
 *        originating from ModelConfig.imageGenerationEnabled stored by Aria)
 *
 *   This two-condition gate ensures that even when a provider declares image capability,
 *   no image output is requested unless the user has explicitly enabled the toggle for
 *   that model in the current conversation.
 */

import type {
  GeneratedImage,
  ModelProvider,
  ModelProviderConfig,
  Message,
  StreamHandler,
  TokenUsage,
  CustomProviderConfig,
  GetCredentialsFn,
  GetPricingTableFn,
} from '@/types';
import { MAX_TOKENS_GENERIC } from './constants';
import {
  mapHttpStatusToErrorCode,
  buildModelError,
  parseSSEStream,
  emitErrorChunk,
  filterMessagesForApi,
} from './openai-sse';

// ─── OpenAI request content types (Phase 5, issue #285) ─────────────────────
//
// Custom endpoints that declare capabilities.vision === true accept multimodal
// content in user messages — the same image_url format as the OpenAI API.
// sendMessage.ts strips attachments before dispatch for non-vision endpoints
// so this formatting only runs when vision is explicitly enabled.

interface GenericTextPart {
  type: 'text';
  text: string;
}

interface GenericImageUrlPart {
  type: 'image_url';
  image_url: { url: string }; // "data:<mimeType>;base64,<base64>"
}

type GenericContentPart = GenericTextPart | GenericImageUrlPart;

// ─── SSE event types emitted by the OpenAI-compatible streaming API ───────────

/**
 * OpenRouter image entry as it appears in the streaming delta.
 * The URL is a data-URL: "data:<mimeType>;base64,<base64>" — the prefix must
 * be stripped before populating GeneratedImage.base64 (issue #376).
 */
interface OpenRouterImageEntry {
  image_url: {
    url: string; // "data:image/png;base64,<base64>"
  };
}

interface OpenAIChoiceDelta {
  content?: string | null;
  role?: string;
  /**
   * OpenRouter-specific: images generated by the model in this chunk.
   * Present only when modalities includes "image" and the model returned image output.
   * Each entry's url is a data-URL — strip the prefix before storing as GeneratedImage.base64.
   * (issue #376)
   */
  images?: OpenRouterImageEntry[];
}

interface OpenAIStreamChoice {
  index: number;
  delta: OpenAIChoiceDelta;
  finish_reason: string | null;
}

interface OpenAIStreamChunk {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: OpenAIStreamChoice[];
  /** Present in the final chunk when stream_options.include_usage is true */
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

// ─── GenericOpenAIProvider ────────────────────────────────────────────────────

export class GenericOpenAIProvider implements ModelProvider {
  readonly config: ModelProviderConfig;

  /** The full CustomProviderConfig supplied at construction. */
  private readonly customConfig: CustomProviderConfig;

  /**
   * Credential lookup function injected at construction time.
   * Stores a function reference, never a key value — the actual API key
   * is only read when sendMessage() calls this function, preserving the
   * "retrieved at call-time, never stored" security rule.
   *
   * sendMessage.ts passes Gate's getCredentials here, which reads from
   * localStorage. This avoids a cross-boundary @/auth import in this file.
   */
  private readonly getCredentialsFn: GetCredentialsFn;

  /**
   * Pricing table lookup injected at construction time (issue #352).
   * Optional — when absent, cost computation is skipped for this provider.
   * sendMessage.ts passes Gate's getPricingTable here. This follows the same
   * dependency-injection rationale as getCredentialsFn: no @/auth import in
   * this file, keeping the @/models boundary clean and preserving test isolation.
   */
  private readonly getPricingTableFn?: GetPricingTableFn;

  constructor(customConfig: CustomProviderConfig, getCredentialsFn: GetCredentialsFn, getPricingTableFn?: GetPricingTableFn) {
    this.customConfig = customConfig;
    this.getCredentialsFn = getCredentialsFn;
    this.getPricingTableFn = getPricingTableFn;
    this.config = {
      modelId: customConfig.id,
      name: customConfig.displayName,
      // color satisfies the ModelProviderConfig contract. Aria does NOT read this
      // field for bubble rendering — it uses ModelConfig.color from rosterToModelConfigs,
      // which reads CustomProviderConfig.color from the roster (Gate) directly.
      // Fall back to 'accent-other' to match the rest of the codebase's unknown-color
      // convention (rosterToModelConfigs uses the same fallback when color is absent).
      color: customConfig.color ?? 'accent-other',
      credentialKey: customConfig.credentialKey ?? '',
    };
  }

  async sendMessage(
    messages: Message[],
    systemPrompt: string | undefined,
    onChunk: StreamHandler,
    selectedVersionId?: string,
    signal?: AbortSignal,
    requestImageGeneration?: boolean
  ): Promise<{ tokenUsage?: TokenUsage }> {
    const { endpointUrl, modelString: defaultModelString, credentialKey, id: modelId } = this.customConfig;

    // selectedVersionId allows callers to override the configured model string.
    // Phase extension point: when sendMessage.ts passes selectedVersionId for custom
    // providers, this resolves to that version rather than the config default.
    const resolvedModelString = selectedVersionId ?? defaultModelString;

    // Retrieve API key at call-time — never store in state.
    //
    // When requiresApiKey is explicitly false, skip the credential lookup entirely.
    // No-auth providers (Ollama, LM Studio, etc.) do not need a key and should
    // not trigger a getCredentials() call that could produce an error or log noise.
    //
    // When requiresApiKey is true or absent (the default), proceed with the normal
    // credential lookup. If credentialKey is present but no key is stored, we
    // proceed with no Authorization header and let the endpoint respond.
    // Remote endpoints that genuinely need a key will respond with 401/403, which
    // mapHttpStatusToErrorCode maps to auth_failure below.
    //
    // This guards all three cases correctly:
    //   - requiresApiKey === false: skip lookup, never set Authorization header.
    //   - requiresApiKey true/absent, credentialKey present, key stored: inject header.
    //   - requiresApiKey true/absent, credentialKey present, key missing: no header;
    //     server returns 401/403 → auth_failure error.
    const apiKey =
      this.customConfig.requiresApiKey !== false && credentialKey
        ? this.getCredentialsFn(credentialKey)
        : undefined;

    // Filter error-only assistant messages from history before sending to the API.
    // OpenAI-compatible endpoints reject requests containing assistant messages with
    // empty content. Such messages are produced when a previous turn failed before
    // emitting any text. filterMessagesForApi strips them to prevent corrupt API calls.
    const filteredMessages = filterMessagesForApi(messages);

    // Map Roundtable Message[] to OpenAI Chat API format.
    // Prepend the system prompt as a system message if provided.
    // Phase 5 (#285): user messages with attachments use typed content-part arrays
    // (image_url parts). sendMessage.ts strips attachments before dispatch for
    // endpoints where capabilities.vision is false or absent, so this path only
    // runs for explicitly vision-capable custom providers.
    const openaiMessages: Array<{
      role: 'system' | 'user' | 'assistant';
      content: string | GenericContentPart[];
    }> = [];

    if (systemPrompt) {
      openaiMessages.push({ role: 'system', content: systemPrompt });
    }

    for (const msg of filteredMessages) {
      if (msg.attachments?.length && msg.role === 'user') {
        const parts: GenericContentPart[] = [];
        if (msg.content) {
          parts.push({ type: 'text', text: msg.content });
        }
        for (const attachment of msg.attachments) {
          parts.push({
            type: 'image_url',
            // Prepend the data-URL prefix — Attachment.base64 is raw (no prefix).
            image_url: { url: `data:${attachment.mimeType};base64,${attachment.base64}` },
          });
        }
        openaiMessages.push({ role: 'user', content: parts });
      } else {
        openaiMessages.push({
          role: msg.role as 'user' | 'assistant',
          content: msg.content,
        });
      }
    }

    // Whether to include stream_options in the request.
    //
    // Reads the static capability declaration from CustomProviderConfig:
    //   - capabilities?.streamUsage === false → skip stream_options unconditionally;
    //     no retry is ever needed because we know this endpoint cannot accept it.
    //   - capabilities?.streamUsage === true or absent (the default) → include
    //     stream_options optimistically and retry once without it if the endpoint
    //     rejects the request (the try/retry path below handles this case).
    //
    // This replaces the former runtime-probe approach (Option B) that used a
    // module-level Set to remember rejecting endpoints across requests. The
    // static declaration eliminates the one extra failed request per session at
    // the cost of requiring the user to declare incompatibility at config time.
    const includeStreamOptions = this.customConfig.capabilities?.streamUsage !== false;

    // Image generation opt-in (issues #376, #379).
    //
    // Both conditions must be true to include modalities: ["image", "text"] in the request:
    //   1. capabilities.imageGeneration === true (static declaration on the provider config)
    //   2. requestImageGeneration === true (per-message user opt-in from ModelConfig.imageGenerationEnabled)
    //
    // The two-condition gate ensures image output is only requested when the user has
    // explicitly enabled the toggle AND the provider declares image capability. Neither
    // condition alone is sufficient — the capability flag without user intent could request
    // images the user didn't want; user intent without capability would be silently ignored
    // by the provider.
    const imageGenEnabled =
      this.customConfig.capabilities?.imageGeneration === true &&
      requestImageGeneration === true;

    // Build a request body with or without stream_options.
    // stream_options.include_usage requests token counts in the final SSE chunk.
    // Some endpoints (e.g. free-tier OpenRouter models backed by third-party
    // inference) reject this parameter with HTTP 422 or 502. This helper is
    // called twice when capabilities?.streamUsage is not false and the endpoint
    // rejects the first request.
    const buildRequestBody = (withStreamOptions: boolean) => ({
      model: resolvedModelString,
      // Use per-provider override when set; fall back to the generic 8192 default (issue #493).
      max_tokens: this.customConfig.maxTokens ?? MAX_TOKENS_GENERIC,
      stream: true,
      ...(withStreamOptions ? { stream_options: { include_usage: true } } : {}),
      // Include modalities only when image gen is explicitly enabled (issue #376).
      // Sending modalities to a model that does not support image output may produce
      // errors or unexpected behavior — gate strictly on the capability flag.
      ...(imageGenEnabled ? { modalities: ['image', 'text'] } : {}),
      messages: openaiMessages,
    });

    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (apiKey) {
      headers['Authorization'] = `Bearer ${apiKey}`;
    }

    let response: Response;
    try {
      response = await fetch(endpointUrl, {
        method: 'POST',
        headers,
        body: JSON.stringify(buildRequestBody(includeStreamOptions)),
        signal,
      });
    } catch (networkErr) {
      // AbortError — user triggered stop before the request completed.
      // Re-throw so runProviderIsolated can identify and swallow it.
      if (networkErr instanceof Error && networkErr.name === 'AbortError') {
        throw networkErr;
      }
      let message = networkErr instanceof Error ? networkErr.message : 'Network request failed';
      // In the dev container the firewall blocks direct HTTPS calls to external APIs.
      // If the endpoint is a direct URL (not already a proxy path), surface a hint.
      if (import.meta.env.DEV && endpointUrl.startsWith('https://')) {
        message += ' — in the dev container, external URLs may be blocked by the firewall. Use a Vite proxy path or add the domain to init-firewall.sh.';
      }
      const error = buildModelError('network_error', message);
      emitErrorChunk(modelId, error, onChunk);
      return {};
    }

    // Auto-retry without stream_options on first non-ok response.
    //
    // When the initial request included stream_options and the endpoint rejected
    // it (HTTP 4xx/5xx), retry once with stream_options omitted. On success the
    // retry response replaces the original and execution continues normally into
    // SSE parsing below.
    //
    // This branch is only reachable when capabilities?.streamUsage is true or
    // absent — when it is explicitly false, includeStreamOptions is false and
    // stream_options is never sent, so this branch is never entered.
    //
    // Constraints:
    //   - Retry only when stream_options was sent (never double-retry).
    //   - Skip retry if the AbortSignal is already fired — respect cancellation.
    //   - Network errors on the retry surface as network_error, not a second retry.
    if (!response.ok && includeStreamOptions) {
      if (!signal?.aborted) {
        try {
          response = await fetch(endpointUrl, {
            method: 'POST',
            headers,
            body: JSON.stringify(buildRequestBody(false)),
            signal,
          });
        } catch (retryNetworkErr) {
          if (retryNetworkErr instanceof Error && retryNetworkErr.name === 'AbortError') {
            throw retryNetworkErr;
          }
          let retryMessage =
            retryNetworkErr instanceof Error
              ? retryNetworkErr.message
              : 'Network request failed';
          if (import.meta.env.DEV && endpointUrl.startsWith('https://')) {
            retryMessage +=
              ' — in the dev container, external URLs may be blocked by the firewall. Use a Vite proxy path or add the domain to init-firewall.sh.';
          }
          emitErrorChunk(modelId, buildModelError('network_error', retryMessage), onChunk);
          return {};
        }
      }
    }

    if (!response.ok) {
      const code = mapHttpStatusToErrorCode(response.status);
      let detail = `HTTP ${response.status}`;
      try {
        const body = await response.json() as { error?: { message?: string } };
        if (body.error?.message) detail = body.error.message;
      } catch {
        // ignore JSON parse failure — use status code detail
      }
      const error = buildModelError(code, detail);
      emitErrorChunk(modelId, error, onChunk);
      return {};
    }

    // ─── Parse SSE stream ──────────────────────────────────────────────────────

    if (!response.body) {
      const error = buildModelError('network_error', 'Response body is not readable');
      emitErrorChunk(modelId, error, onChunk);
      return {};
    }

    let inputTokens = 0;
    let outputTokens = 0;
    // Accumulate image parts encountered across streaming chunks (issue #376).
    // OpenRouter returns generated images in choices[].delta.images[] as data-URLs.
    // The data-URL prefix ("data:<mimeType>;base64,") is stripped before storing
    // to match the GeneratedImage.base64 convention (no prefix). Emitted on the
    // final done chunk only; undefined (not []) when no images were returned.
    const collectedImages: GeneratedImage[] = [];

    try {
      for await (const data of parseSSEStream(response)) {
        let event: OpenAIStreamChunk;
        try {
          event = JSON.parse(data) as OpenAIStreamChunk;
        } catch {
          continue;
        }

        // Capture token usage from the final usage chunk (stream_options.include_usage).
        // If the endpoint does not return usage, inputTokens and outputTokens stay zero
        // and we still emit a valid done chunk.
        if (event.usage) {
          inputTokens = event.usage.prompt_tokens;
          outputTokens = event.usage.completion_tokens;
        }

        // Emit content deltas; collect image outputs (issue #376).
        for (const choice of event.choices) {
          const text = choice.delta.content;
          if (text) {
            onChunk({
              modelId,
              content: text,
              isDone: false,
            });
          }

          // Collect images from OpenRouter's delta.images[] (issue #376).
          // images[] is only present when modalities includes "image" and the model
          // returned image content. Each entry is a data-URL — strip the prefix to
          // extract raw base64 before storing as GeneratedImage.base64.
          if (imageGenEnabled && choice.delta.images?.length) {
            for (const imgEntry of choice.delta.images) {
              const dataUrl = imgEntry.image_url?.url;
              if (!dataUrl) continue;

              // Parse "data:<mimeType>;base64,<base64>" into mimeType + raw base64.
              // Pattern: "data:" + mimeType + ";base64," + <base64data>
              const commaIdx = dataUrl.indexOf(',');
              if (commaIdx === -1) continue; // malformed data-URL — skip

              const metaPart = dataUrl.slice('data:'.length, commaIdx); // e.g. "image/png;base64"
              const base64Data = dataUrl.slice(commaIdx + 1);
              const mimeType = metaPart.includes(';') ? metaPart.split(';')[0] : metaPart;

              if (!base64Data || !mimeType) continue;

              collectedImages.push({
                id: crypto.randomUUID(),
                mimeType,
                base64: base64Data,
              });
            }
          }
        }
      }
    } catch (streamErr) {
      // AbortError — user triggered stop mid-stream.
      // Emit a clean done chunk with whatever tokens and images were collected so far,
      // then re-throw so runProviderIsolated can identify and swallow it.
      if (streamErr instanceof Error && streamErr.name === 'AbortError') {
        onChunk({
          modelId,
          content: '',
          isDone: true,
          tokenUsage: {
            inputTokens,
            outputTokens,
            totalTokens: inputTokens + outputTokens,
          },
          images: collectedImages.length > 0 ? collectedImages : undefined,
        });
        throw streamErr;
      }
      const error = buildModelError(
        'network_error',
        streamErr instanceof Error ? streamErr.message : 'Stream read failed'
      );
      emitErrorChunk(modelId, error, onChunk);
      return {};
    }

    // Emit final done chunk with token usage
    const tokenUsage: TokenUsage = {
      inputTokens,
      outputTokens,
      totalTokens: inputTokens + outputTokens,
    };

    // Compute estimated cost if pricing data is available for this model string.
    // Missing entry or null table means cost is unknown — do not set to 0.
    // getPricingTableFn is injected at construction time — absent when the caller
    // does not supply it (e.g. tests that construct the provider directly).
    if (this.getPricingTableFn) {
      const pricingTable = this.getPricingTableFn();
      const pricingEntry = pricingTable?.[resolvedModelString];
      if (pricingEntry) {
        tokenUsage.estimatedCost =
          (tokenUsage.inputTokens / 1_000_000) * pricingEntry.inputPer1M +
          (tokenUsage.outputTokens / 1_000_000) * pricingEntry.outputPer1M;
      }
    }

    onChunk({
      modelId,
      content: '',
      isDone: true,
      tokenUsage,
      // images is undefined (not []) when no images were returned, per StreamChunk contract.
      images: collectedImages.length > 0 ? collectedImages : undefined,
    });

    return { tokenUsage };
  }
}

// ─── Factory function ─────────────────────────────────────────────────────────

/**
 * Construct a GenericOpenAIProvider from a CustomProviderConfig.
 * Used by sendMessage.ts dispatch (ticket #95) when building the active
 * provider list from the user's ProviderRoster.
 *
 * getCredentialsFn is Gate's getCredentials function, passed in by the caller
 * (sendMessage.ts) which already imports from @/auth. This avoids a
 * cross-boundary @/auth import here in @/models.
 *
 * getPricingTableFn is Gate's getPricingTable function, also passed by
 * sendMessage.ts (issue #352). Optional — when absent, cost computation is
 * skipped. Dependency-injected to keep generic.ts free of @/auth imports and
 * to preserve test isolation (tests constructing GenericOpenAIProvider directly
 * do not supply this and therefore never trigger a background pricing fetch).
 */
export function createCustomProvider(
  config: CustomProviderConfig,
  getCredentialsFn: GetCredentialsFn,
  getPricingTableFn?: GetPricingTableFn,
): GenericOpenAIProvider {
  return new GenericOpenAIProvider(config, getCredentialsFn, getPricingTableFn);
}
