/**
 * Gate — providerRoster.ts
 *
 * CRUD operations for the ProviderRoster, stored in localStorage under the key
 * "roundtable:provider-roster". The roster is the canonical record of which
 * providers (built-in and custom) the user has configured.
 *
 * Atlas reads the roster to know which providers to instantiate and dispatch to.
 * Aria reads the roster to populate the model selector.
 *
 * Storage rules (non-negotiable):
 *   - localStorage is the sole persistence layer
 *   - Reads never throw — any parse error returns []
 *   - An empty roster is valid (user has configured no providers)
 *   - Custom IDs are generated by Gate and must never collide with BuiltInModelId values
 */

import type {
  BuiltInCredentialKey,
  BuiltInModelId,
  BuiltInProviderConfig,
  CustomProviderConfig,
  ProviderConfig,
  ProviderRoster,
} from '@/types';
import { MODEL_CREDENTIAL_MAP } from './credentials';

// ─── Storage key ──────────────────────────────────────────────────────────────

const ROSTER_STORAGE_KEY = 'roundtable:provider-roster' as const;

// ─── Validation helpers ────────────────────────────────────────────────────────

/**
 * The set of known BuiltInModelId values. Used to discriminate deserialized
 * entries — entries whose modelId (built-in) or id (custom) is structurally
 * invalid are dropped.
 */
const BUILTIN_MODEL_IDS: ReadonlySet<BuiltInModelId> = new Set<BuiltInModelId>([
  'claude',
  'gpt-5.5',
  'gemini',
  'grok',
  'deepseek',
  'mistral',
]);

const BUILTIN_CREDENTIAL_KEYS: ReadonlySet<BuiltInCredentialKey> = new Set<BuiltInCredentialKey>([
  'anthropic',
  'openai',
  'google',
  'xai',
  'deepseek',
  'mistral',
]);

function isBuiltInModelId(value: unknown): value is BuiltInModelId {
  return typeof value === 'string' && BUILTIN_MODEL_IDS.has(value as BuiltInModelId);
}

function isBuiltInCredentialKey(value: unknown): value is BuiltInCredentialKey {
  return typeof value === 'string' && BUILTIN_CREDENTIAL_KEYS.has(value as BuiltInCredentialKey);
}

/**
 * Validate that a deserialized object is a structurally valid BuiltInProviderConfig.
 * Drops any entry that doesn't conform — fail closed.
 */
function isValidBuiltInConfig(value: unknown): value is BuiltInProviderConfig {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    v['kind'] === 'builtin' &&
    isBuiltInModelId(v['modelId']) &&
    isBuiltInCredentialKey(v['credentialKey']) &&
    typeof v['isVisible'] === 'boolean' &&
    (v['selectedVersionId'] === undefined || typeof v['selectedVersionId'] === 'string')
  );
}

/**
 * Validate that a deserialized object is a structurally valid CustomProviderConfig.
 * Drops any entry that doesn't conform — fail closed.
 */
function isValidCustomConfig(value: unknown): value is CustomProviderConfig {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    v['kind'] === 'custom' &&
    typeof v['id'] === 'string' &&
    (v['id'] as string).length > 0 &&
    typeof v['displayName'] === 'string' &&
    (v['displayName'] as string).length > 0 &&
    typeof v['endpointUrl'] === 'string' &&
    (v['endpointUrl'] as string).length > 0 &&
    typeof v['modelString'] === 'string' &&
    (v['modelString'] as string).length > 0 &&
    (v['credentialKey'] === undefined || typeof v['credentialKey'] === 'string') &&
    (v['color'] === undefined || typeof v['color'] === 'string')
  );
}

// ─── Internal read/write helpers ──────────────────────────────────────────────

/**
 * Read and validate the roster from localStorage.
 * Silently drops any entry that fails validation.
 * Returns [] on any error or if the key is absent.
 */
function readRoster(): ProviderRoster {
  let raw: string | null;
  try {
    raw = localStorage.getItem(ROSTER_STORAGE_KEY);
  } catch {
    return [];
  }

  if (raw === null) return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return [];
  }

  if (!Array.isArray(parsed)) return [];

  const result: ProviderRoster = [];
  for (const entry of parsed) {
    if (isValidBuiltInConfig(entry)) {
      result.push(entry);
    } else if (isValidCustomConfig(entry)) {
      result.push(entry);
    }
    // Silently drop entries that fail validation.
  }

  return result;
}

/**
 * Write the roster to localStorage.
 */
function writeRoster(roster: ProviderRoster): void {
  localStorage.setItem(ROSTER_STORAGE_KEY, JSON.stringify(roster));
}

// ─── Slug helper ──────────────────────────────────────────────────────────────

/**
 * Convert a display name to a URL-safe slug.
 * e.g. "My OpenRouter Config" → "my-openrouter-config"
 */
function slugify(displayName: string): string {
  return displayName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'provider';
}

/**
 * Generate a collision-safe custom provider ID.
 * Format: "custom:<slug>" or "custom:<slug>-<n>" if the base collides.
 *
 * Collisions are checked against the current roster AND the BuiltInModelId set
 * (a custom ID must never equal a built-in model ID).
 */
function generateCustomId(displayName: string, existingRoster: ProviderRoster): string {
  const slug = slugify(displayName);
  const base = `custom:${slug}`;

  const existingIds = new Set<string>([
    ...BUILTIN_MODEL_IDS,
    ...existingRoster.map((p) => (p.kind === 'builtin' ? p.modelId : p.id)),
  ]);

  if (!existingIds.has(base)) return base;

  let n = 2;
  while (existingIds.has(`${base}-${n}`)) {
    n++;
  }
  return `${base}-${n}`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Retrieve the user's full provider roster.
 *
 * Parses from localStorage. Returns [] if absent or unparseable.
 * Never throws.
 */
export function getProviderRoster(): ProviderRoster {
  return readRoster();
}

/**
 * Persist the full provider roster to localStorage.
 *
 * Replaces any existing stored roster entirely.
 * Callers are responsible for passing a valid roster.
 */
export function saveProviderRoster(roster: ProviderRoster): void {
  writeRoster(roster);
}

/**
 * Add a built-in provider to the roster and save.
 *
 * Creates a BuiltInProviderConfig with kind:'builtin', isVisible:true, and no
 * selectedVersionId. The credentialKey is derived from MODEL_CREDENTIAL_MAP.
 *
 * No-op if the built-in model is already present in the roster — returns the
 * existing entry in that case.
 *
 * Returns the new (or existing) BuiltInProviderConfig entry.
 */
export function addBuiltInProvider(modelId: BuiltInModelId): BuiltInProviderConfig {
  const roster = readRoster();

  const existing = roster.find(
    (p): p is BuiltInProviderConfig => p.kind === 'builtin' && p.modelId === modelId
  );
  if (existing) return existing;

  const newEntry: BuiltInProviderConfig = {
    kind: 'builtin',
    modelId,
    credentialKey: MODEL_CREDENTIAL_MAP[modelId],
    isVisible: true,
  };

  writeRoster([...roster, newEntry]);
  return newEntry;
}

/**
 * Add a custom OpenAI-compatible provider to the roster and save.
 *
 * Generates a collision-safe id (prefix "custom:" + slug from displayName).
 * If credentialKey is not supplied, generates it as "custom:<id>".
 *
 * Returns the new CustomProviderConfig entry.
 */
export function addCustomProvider(input: {
  displayName: string;
  endpointUrl: string;
  modelString: string;
  credentialKey?: string;
  color?: string;
}): CustomProviderConfig {
  const roster = readRoster();
  const id = generateCustomId(input.displayName, roster);

  const newEntry: CustomProviderConfig = {
    kind: 'custom',
    id,
    displayName: input.displayName,
    endpointUrl: input.endpointUrl,
    modelString: input.modelString,
    credentialKey: input.credentialKey ?? `custom:${id}`,
    ...(input.color !== undefined ? { color: input.color } : {}),
  };

  writeRoster([...roster, newEntry]);
  return newEntry;
}

/**
 * Remove a provider from the roster by its identifier.
 *
 * For built-in providers: match on `modelId`.
 * For custom providers: match on `id`.
 *
 * The `id` parameter should be the BuiltInModelId for built-ins (e.g. 'claude')
 * or the generated id string for custom providers (e.g. 'custom:openrouter-1').
 *
 * No-op if no provider with that identifier exists in the roster.
 */
export function removeProvider(id: string): void {
  const roster = readRoster();
  const filtered = roster.filter((p) => {
    if (p.kind === 'builtin') return p.modelId !== id;
    return p.id !== id;
  });

  if (filtered.length === roster.length) return; // Nothing removed — no write needed.
  writeRoster(filtered);
}

/**
 * Update the editable fields of an existing custom provider.
 *
 * Applies displayName, endpointUrl, modelString, and optionally color to the
 * matching custom entry in the roster. `credentialKey` and `id` are never
 * changed — they are stable identifiers; `credentialKey` in particular links
 * the provider to its stored API key and must survive edits.
 *
 * No-op if:
 *   - No provider with the given `id` exists in the roster.
 *   - The matching entry is not a custom provider (kind !== 'custom').
 */
export function updateCustomProvider(
  id: string,
  input: {
    displayName: string;
    endpointUrl: string;
    modelString: string;
    color?: string;
  },
): void {
  const roster = readRoster();

  let found = false;
  const updated = roster.map((p): ProviderConfig => {
    if (p.kind !== 'custom' || p.id !== id) return p;
    found = true;
    const entry: CustomProviderConfig = {
      ...p,
      displayName: input.displayName,
      endpointUrl: input.endpointUrl,
      modelString: input.modelString,
    };
    if (input.color !== undefined) {
      entry.color = input.color;
    } else {
      delete entry.color;
    }
    return entry;
  });

  if (!found) return; // No matching custom provider — no write needed.
  writeRoster(updated);
}

/**
 * Find a provider in the roster by its identifier.
 *
 * For built-in providers: matches on `modelId`.
 * For custom providers: matches on `id`.
 *
 * Returns undefined if no matching provider is found.
 */
export function getProviderById(id: string): ProviderConfig | undefined {
  const roster = readRoster();
  return roster.find((p) => {
    if (p.kind === 'builtin') return p.modelId === id;
    return p.id === id;
  });
}
