/**
 * Gate — providerRoster.ts
 *
 * CRUD operations for the ProviderRoster, stored in localStorage under the key
 * "roundtable:provider-roster". The roster is the canonical record of which
 * providers (built-in and custom) the user has configured.
 *
 * Atlas reads the roster to know which providers to instantiate and dispatch to.
 * Aria reads the roster to populate the model selector.
 *
 * Storage rules (non-negotiable):
 *   - localStorage is the sole persistence layer
 *   - Reads never throw — any parse error returns []
 *   - An empty roster is valid (user has configured no providers)
 *   - Custom IDs are generated by Gate and must never collide with BuiltInModelId values
 */

import type {
  BuiltInCredentialKey,
  BuiltInModelId,
  BuiltInProviderConfig,
  CustomProviderConfig,
  ProviderCapabilities,
  ProviderConfig,
  ProviderRoster,
} from '@/types';
import { MODEL_CREDENTIAL_MAP } from './credentials';
import { BUILTIN_MODEL_IDS } from './builtinModelIds';

// ─── Storage key ──────────────────────────────────────────────────────────────

const ROSTER_STORAGE_KEY = 'roundtable:provider-roster' as const;

// ─── Built-in capabilities ────────────────────────────────────────────────────

/**
 * Canonical capability declarations for all six built-in providers.
 *
 * Gate owns this map. It is the single source of truth for which built-in
 * providers support vision, streaming usage, tool use, and system prompts.
 *
 * Design note: this is an intentional Gate-local copy — not imported from
 * @/models. Atlas owns its own provider implementations; Gate owns the
 * persisted ProviderCapabilities used by Aria and Atlas to make request
 * decisions. The two must agree, but a direct import would create a
 * cross-boundary dependency that violates agent boundary rules.
 *
 * Capabilities are conservative by default: when a built-in does not have
 * confirmed support for a feature, the field is set to false or omitted so
 * Atlas never sends unsupported request parameters to that provider.
 *
 * Aria reads `config.capabilities?.vision` (from the roster) to show the
 * pre-send warning modal when the user attaches images to a message
 * addressed to a non-vision provider. Atlas reads the same field to decide
 * whether to include image content parts in the request body.
 *
 * Typed as Record<BuiltInModelId, ProviderCapabilities> — TypeScript enforces
 * exhaustiveness at compile time. Adding a new BuiltInModelId to the union
 * requires adding an entry here; the compiler will error until it is present.
 */
const BUILTIN_CAPABILITIES_MAP: Record<BuiltInModelId, ProviderCapabilities> = {
  // Anthropic Claude: full multimodal + streaming usage + tools + system prompts.
  'claude': { vision: true, streamUsage: true, toolUse: true, systemPrompt: true },
  // OpenAI GPT: full multimodal + streaming usage + tools + system prompts.
  'gpt-5.5': { vision: true, streamUsage: true, toolUse: true, systemPrompt: true, imageGeneration: true },
  // Google Gemini: vision + tools + system prompts; no streamUsage (streaming
  // token counts not available via the OpenAI-compat endpoint Gate uses).
  'gemini': { vision: true, streamUsage: false, toolUse: true, systemPrompt: true, imageGeneration: true },
  // xAI Grok: vision support unconfirmed — conservative default.
  'grok': { vision: false },
  // DeepSeek: vision support unconfirmed — conservative default.
  'deepseek': { vision: false },
  // Mistral: vision support unconfirmed — conservative default.
  'mistral': { vision: false },
};

// ─── Validation helpers ────────────────────────────────────────────────────────

// BUILTIN_MODEL_IDS imported from builtinModelIds.ts — canonical single source.

const BUILTIN_CREDENTIAL_KEYS: ReadonlySet<BuiltInCredentialKey> = new Set<BuiltInCredentialKey>([
  'anthropic',
  'openai',
  'google',
  'xai',
  'deepseek',
  'mistral',
]);

function isBuiltInModelId(value: unknown): value is BuiltInModelId {
  return typeof value === 'string' && BUILTIN_MODEL_IDS.has(value as BuiltInModelId);
}

function isBuiltInCredentialKey(value: unknown): value is BuiltInCredentialKey {
  return typeof value === 'string' && BUILTIN_CREDENTIAL_KEYS.has(value as BuiltInCredentialKey);
}

/**
 * Validate that a deserialized value is a structurally valid ProviderCapabilities object.
 *
 * All fields are optional booleans. Absence of the `capabilities` field on a
 * CustomProviderConfig is allowed — Atlas uses per-capability defaults in that case.
 * When present, the value must be a plain object with only optional boolean fields;
 * any non-boolean field value is rejected (fail closed).
 */
function isValidCapabilities(value: unknown): value is ProviderCapabilities {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  const knownFields: Array<keyof ProviderCapabilities> = [
    'streamUsage',
    'vision',
    'toolUse',
    'systemPrompt',
    'imageGeneration',
    'thinking',
    'structuredOutputs',
    'contextManagement',
  ];
  for (const field of knownFields) {
    if (v[field] !== undefined && typeof v[field] !== 'boolean') return false;
  }
  return true;
}

/**
 * Validate that a deserialized object is a structurally valid BuiltInProviderConfig.
 * Drops any entry that doesn't conform — fail closed.
 */
function isValidBuiltInConfig(value: unknown): value is BuiltInProviderConfig {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    v['kind'] === 'builtin' &&
    isBuiltInModelId(v['modelId']) &&
    isBuiltInCredentialKey(v['credentialKey']) &&
    typeof v['isVisible'] === 'boolean' &&
    (v['selectedVersionId'] === undefined || typeof v['selectedVersionId'] === 'string')
  );
}

/**
 * Validate that a deserialized object is a structurally valid CustomProviderConfig.
 * Drops any entry that doesn't conform — fail closed.
 *
 * `capabilities` is optional. When present, it must pass `isValidCapabilities`.
 * Existing records without `capabilities` continue to pass — Atlas uses per-capability
 * defaults for any absent field.
 */
function isValidCustomConfig(value: unknown): value is CustomProviderConfig {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    v['kind'] === 'custom' &&
    typeof v['id'] === 'string' &&
    (v['id'] as string).length > 0 &&
    typeof v['displayName'] === 'string' &&
    (v['displayName'] as string).length > 0 &&
    typeof v['endpointUrl'] === 'string' &&
    (v['endpointUrl'] as string).length > 0 &&
    typeof v['modelString'] === 'string' &&
    (v['modelString'] as string).length > 0 &&
    (v['credentialKey'] === undefined || typeof v['credentialKey'] === 'string') &&
    (v['color'] === undefined || typeof v['color'] === 'string') &&
    (v['requiresApiKey'] === undefined || typeof v['requiresApiKey'] === 'boolean') &&
    (v['capabilities'] === undefined || isValidCapabilities(v['capabilities']))
  );
}

// ─── Internal read/write helpers ──────────────────────────────────────────────

/**
 * Read and validate the roster from localStorage.
 * Silently drops any entry that fails validation.
 * Returns [] on any error or if the key is absent.
 */
function readRoster(): ProviderRoster {
  let raw: string | null;
  try {
    raw = localStorage.getItem(ROSTER_STORAGE_KEY);
  } catch {
    return [];
  }

  if (raw === null) return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return [];
  }

  if (!Array.isArray(parsed)) return [];

  const result: ProviderRoster = [];
  for (const entry of parsed) {
    if (isValidBuiltInConfig(entry)) {
      // Always use BUILTIN_CAPABILITIES_MAP as the authoritative source for
      // built-in capabilities. Stored values may be stale (missing flags added
      // in later releases, e.g. imageGeneration added in #379). The map is
      // code-defined and always current; localStorage is just a cache.
      result.push({ ...entry, capabilities: BUILTIN_CAPABILITIES_MAP[entry.modelId] });
    } else if (isValidCustomConfig(entry)) {
      result.push(entry);
    }
    // Silently drop entries that fail validation.
  }

  return result;
}

/**
 * Write the roster to localStorage.
 */
function writeRoster(roster: ProviderRoster): void {
  localStorage.setItem(ROSTER_STORAGE_KEY, JSON.stringify(roster));
}

// ─── Slug helper ──────────────────────────────────────────────────────────────

/**
 * Convert a display name to a URL-safe slug.
 * e.g. "My OpenRouter Config" → "my-openrouter-config"
 */
function slugify(displayName: string): string {
  return displayName
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'provider';
}

/**
 * Generate a collision-safe custom provider ID.
 * Format: "custom:<slug>" or "custom:<slug>-<n>" if the base collides.
 *
 * Collisions are checked against the current roster AND the BuiltInModelId set
 * (a custom ID must never equal a built-in model ID).
 */
function generateCustomId(displayName: string, existingRoster: ProviderRoster): string {
  const slug = slugify(displayName);
  const base = `custom:${slug}`;

  const existingIds = new Set<string>([
    ...BUILTIN_MODEL_IDS,
    ...existingRoster.map((p) => (p.kind === 'builtin' ? p.modelId : p.id)),
  ]);

  if (!existingIds.has(base)) return base;

  let n = 2;
  while (existingIds.has(`${base}-${n}`)) {
    n++;
  }
  return `${base}-${n}`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Retrieve the user's full provider roster.
 *
 * Parses from localStorage. Returns [] if absent or unparseable.
 * Never throws.
 */
export function getProviderRoster(): ProviderRoster {
  return readRoster();
}

/**
 * Persist the full provider roster to localStorage.
 *
 * Replaces any existing stored roster entirely.
 * Callers are responsible for passing a valid roster.
 */
export function saveProviderRoster(roster: ProviderRoster): void {
  writeRoster(roster);
}

/**
 * Add a built-in provider to the roster and save.
 *
 * Creates a BuiltInProviderConfig with kind:'builtin', isVisible:true, and no
 * selectedVersionId. The credentialKey is derived from MODEL_CREDENTIAL_MAP.
 *
 * No-op if the built-in model is already present in the roster — returns the
 * existing entry in that case.
 *
 * Returns the new (or existing) BuiltInProviderConfig entry.
 */
export function addBuiltInProvider(modelId: BuiltInModelId): BuiltInProviderConfig {
  const roster = readRoster();

  const existing = roster.find(
    (p): p is BuiltInProviderConfig => p.kind === 'builtin' && p.modelId === modelId
  );
  if (existing) return existing;

  const newEntry: BuiltInProviderConfig = {
    kind: 'builtin',
    modelId,
    credentialKey: MODEL_CREDENTIAL_MAP[modelId],
    isVisible: true,
    capabilities: BUILTIN_CAPABILITIES_MAP[modelId],
  };

  writeRoster([...roster, newEntry]);
  return newEntry;
}

/**
 * Add a custom OpenAI-compatible provider to the roster and save.
 *
 * Generates a collision-safe id (prefix "custom:" + slug from displayName).
 * If credentialKey is not supplied, generates it as "custom:<id>".
 *
 * When `requiresApiKey` is `false`, the provider is treated as keyless (e.g.
 * a local Ollama instance). The `credentialKey` is still generated and stored
 * for forward-compatibility, but no credential value is required or checked.
 * When absent, `requiresApiKey` defaults to `true` — all existing callers are
 * unaffected.
 *
 * When `capabilities` is provided, it is stored verbatim on the entry. Absence
 * means Atlas uses its per-capability defaults for every field. Aria passes this
 * when the user configures capability toggles at provider-creation time.
 *
 * Returns the new CustomProviderConfig entry.
 */
export function addCustomProvider(input: {
  displayName: string;
  endpointUrl: string;
  modelString: string;
  credentialKey?: string;
  color?: string;
  requiresApiKey?: boolean;
  capabilities?: ProviderCapabilities;
}): CustomProviderConfig {
  const roster = readRoster();
  const id = generateCustomId(input.displayName, roster);

  const newEntry: CustomProviderConfig = {
    kind: 'custom',
    id,
    displayName: input.displayName,
    endpointUrl: input.endpointUrl,
    modelString: input.modelString,
    credentialKey: input.credentialKey ?? `custom:${id}`,
    ...(input.color !== undefined ? { color: input.color } : {}),
    // Only store requiresApiKey when explicitly set to false. Absence and true
    // are equivalent; storing true explicitly is unnecessary noise in localStorage.
    ...(input.requiresApiKey === false ? { requiresApiKey: false } : {}),
    // Only store capabilities when explicitly provided.
    ...(input.capabilities !== undefined ? { capabilities: input.capabilities } : {}),
  };

  writeRoster([...roster, newEntry]);
  return newEntry;
}

/**
 * Remove a provider from the roster by its identifier.
 *
 * For built-in providers: match on `modelId`.
 * For custom providers: match on `id`.
 *
 * The `id` parameter should be the BuiltInModelId for built-ins (e.g. 'claude')
 * or the generated id string for custom providers (e.g. 'custom:openrouter-1').
 *
 * No-op if no provider with that identifier exists in the roster.
 */
export function removeProvider(id: string): void {
  const roster = readRoster();
  const filtered = roster.filter((p) => {
    if (p.kind === 'builtin') return p.modelId !== id;
    return p.id !== id;
  });

  if (filtered.length === roster.length) return; // Nothing removed — no write needed.
  writeRoster(filtered);
}

/**
 * Update the editable fields of an existing custom provider.
 *
 * Applies displayName, endpointUrl, modelString, color, requiresApiKey, and
 * capabilities to the matching custom entry in the roster. `credentialKey` and
 * `id` are never changed — they are stable identifiers; `credentialKey` in
 * particular links the provider to its stored API key and must survive edits.
 *
 * `requiresApiKey` defaults to `true` when not supplied. Pass `false` explicitly
 * to mark a provider as keyless (e.g. a local Ollama instance).
 *
 * `capabilities` follows the same pattern as `color`: when present in the input,
 * it replaces the stored value; when absent (undefined), the stored `capabilities`
 * field is removed. Aria's edit form must pass the current capability values when
 * saving — omitting `capabilities` clears any previously stored overrides.
 *
 * No-op if:
 *   - No provider with the given `id` exists in the roster.
 *   - The matching entry is not a custom provider (kind !== 'custom').
 */
export function updateCustomProvider(
  id: string,
  input: {
    displayName: string;
    endpointUrl: string;
    modelString: string;
    color?: string;
    requiresApiKey?: boolean;
    capabilities?: ProviderCapabilities;
  },
): void {
  const roster = readRoster();

  let found = false;
  const updated = roster.map((p): ProviderConfig => {
    if (p.kind !== 'custom' || p.id !== id) return p;
    found = true;
    const entry: CustomProviderConfig = {
      ...p,
      displayName: input.displayName,
      endpointUrl: input.endpointUrl,
      modelString: input.modelString,
    };
    if (input.color !== undefined) {
      entry.color = input.color;
    } else {
      delete entry.color;
    }
    // Only store requiresApiKey when explicitly false; absence === true.
    if (input.requiresApiKey === false) {
      entry.requiresApiKey = false;
    } else {
      delete entry.requiresApiKey;
    }
    // Store capabilities when provided; clear when absent (same semantics as color).
    if (input.capabilities !== undefined) {
      entry.capabilities = input.capabilities;
    } else {
      delete entry.capabilities;
    }
    return entry;
  });

  if (!found) return; // No matching custom provider — no write needed.
  writeRoster(updated);
}

/**
 * Find a provider in the roster by its identifier.
 *
 * For built-in providers: matches on `modelId`.
 * For custom providers: matches on `id`.
 *
 * Returns undefined if no matching provider is found.
 */
export function getProviderById(id: string): ProviderConfig | undefined {
  const roster = readRoster();
  return roster.find((p) => {
    if (p.kind === 'builtin') return p.modelId === id;
    return p.id === id;
  });
}
